import type { ClassDefinition, SubclassDefinition } from "@/config/types";

const noSpellcasting = {
  type: "none" as const,
  ability: "strength" as const,
  preparation: "none" as const,
  startsAtLevel: 0,
};

export const CLASSES: ClassDefinition[] = [
  // ─── BÁRBARO ───────────────────────────────────────────
  {
    id: "barbarian",
    name: "Bárbaro",
    hitDie: 12,
    primaryAbilities: ["strength"],
    savingThrows: ["strength", "constitution"],
    armorProficiencies: ["leves", "médias", "escudos"],
    weaponProficiencies: ["simples", "marciais"],
    toolProficiencies: [],
    skillChoices: {
      choose: 2,
      from: ["animalHandling", "athletics", "intimidation", "nature", "perception", "survival"],
    },
    subclassLevel: 3,
    spellcasting: noSpellcasting,
    startingEquipment: [
      "Machado grande ou qualquer arma marcial corpo a corpo",
      "Duas machadinhas ou qualquer arma simples",
      "Pacote de explorador e quatro azagaias",
    ],
    startingGoldDice: "2d4×10",
    features: [
      { level: 1, name: "Fúria", description: "Em combate, você pode entrar em fúria como ação bônus. Enquanto em fúria (se não usar armadura pesada): vantagem em testes e salvaguardas de Força; bônus de dano de fúria em ataques corpo a corpo com Força; resistência a concussão, perfurante e cortante. Dura 1 minuto. Usos por descanso longo conforme nível." },
      { level: 1, name: "Defesa sem Armadura", description: "Enquanto não usar armadura, sua CA é 10 + modificador de Destreza + modificador de Constituição. Pode usar escudo e ainda se beneficiar." },
      { level: 2, name: "Ataque Imprudente", description: "No seu primeiro ataque no turno, pode atacar de forma imprudente: vantagem em ataques corpo a corpo com Força neste turno, mas ataques contra você têm vantagem até seu próximo turno." },
      { level: 2, name: "Sentido de Perigo", description: "Vantagem em salvaguardas de Destreza contra efeitos que você possa ver, se não estiver incapacitado." },
      { level: 3, name: "Caminho Primal", description: "Escolha um caminho primal que molda a natureza da sua fúria." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois atributos em 1, ou escolha um talento (se o Mestre permitir)." },
      { level: 5, name: "Ataque Extra", description: "Pode atacar duas vezes sempre que tomar a ação Ataque no seu turno." },
      { level: 5, name: "Movimento Rápido", description: "Seu deslocamento aumenta em 3 metros enquanto não usar armadura pesada." },
      { level: 6, name: "Característica do Caminho", description: "Você ganha uma característica do seu caminho primal." },
      { level: 7, name: "Instinto Selvagem", description: "Vantagem em jogadas de iniciativa. Se for surpreendido e não estiver incapacitado, pode agir normalmente no seu primeiro turno se entrar em fúria." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois atributos em 1, ou escolha um talento." },
      { level: 9, name: "Crítico Brutal", description: "Role um dado de dano de arma adicional ao determinar o dano extra de um acerto crítico com ataque corpo a corpo. Aumenta nos níveis 13 e 17." },
      { level: 10, name: "Característica do Caminho", description: "Você ganha uma característica do seu caminho primal." },
      { level: 11, name: "Fúria Implacável", description: "Se cair a 0 PV enquanto em fúria e não morrer, pode fazer salvaguarda de Constituição (CD 10 + danos sofridos desde o último turno). Em sucesso, fica com 1 PV. CD aumenta em 5 a cada uso até descanso." },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois atributos em 1, ou escolha um talento." },
      { level: 13, name: "Crítico Brutal", description: "Role dois dados de dano de arma adicionais em críticos corpo a corpo." },
      { level: 14, name: "Característica do Caminho", description: "Você ganha uma característica do seu caminho primal." },
      { level: 15, name: "Fúria Persistente", description: "Sua fúria só termina antecipadamente se você cair inconsciente ou escolher terminá-la." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois atributos em 1, ou escolha um talento." },
      { level: 17, name: "Crítico Brutal", description: "Role três dados de dano de arma adicionais em críticos corpo a corpo." },
      { level: 18, name: "Poder Indomável", description: "Se o total de um teste de Força for menor que sua Força, pode usar sua Força em vez do total." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois atributos em 1, ou escolha um talento." },
      { level: 20, name: "Campeão Primal", description: "Força e Constituição aumentam em 4. O máximo para esses atributos é agora 24." },
    ],
    subclasses: [
      {
        id: "berserker",
        name: "Caminho do Berserker",
        description: "Para alguns bárbaros, a fúria é um meio para um fim — essa finalidade sendo a violência. O Caminho do Berserker é um caminho de fúria desenfreada, alimentando a fúria com uma frenesi sangrenta.",
        features: [
          { level: 3, name: "Frenesi", description: "Pode entrar em frenesi ao entrar em fúria. Enquanto frenético, pode fazer um único ataque corpo a corpo como ação bônus em cada turno. Quando a fúria termina, sofre um nível de exaustão." },
          { level: 6, name: "Fúria Mentecapaz", description: "Não pode ser enfeitiçado ou amedrontado enquanto em fúria. Se já estiver enfeitiçado ou amedrontado ao entrar em fúria, o efeito é suspenso pela duração da fúria." },
          { level: 10, name: "Presença Intimidante", description: "Como ação, pode amedrontar uma criatura a até 9 m com salvaguarda de Sabedoria. Em falha, fica amedrontada até o fim do seu próximo turno. Pode usar ação para estender." },
          { level: 14, name: "Retaliação", description: "Quando sofrer dano de uma criatura a até 1,5 m, pode usar reação para fazer um ataque corpo a corpo contra ela." },
        ],
      },
      {
        id: "totem",
        name: "Caminho do Guerreiro Totêmico",
        description: "O Caminho do Guerreiro Totêmico é um caminho espiritual, aceitando um espírito animal como guia, protetor e inspiração.",
        features: [
          { level: 3, name: "Buscador de Espíritos", description: "Ganha a habilidade de conjurar sentido animal e falar com animais, mas apenas como rituais." },
          { level: 3, name: "Totem Espiritual", description: "Escolha um animal totêmico (Urso: resistência a todos os danos exceto psíquico; Águia: outros têm desvantagem em ataques de oportunidade e pode Disparada como ação bônus; Lobo: aliados têm vantagem em ataques corpo a corpo contra inimigos a 1,5 m de você) enquanto em fúria." },
          { level: 6, name: "Aspecto da Fera", description: "Ganhe um benefício mágico do seu totêmico (Urso: capacidade de carga dobrada; Águia: visão a 1,6 km; Lobo: ritmo de viagem rápido sem exaustão do grupo)." },
          { level: 10, name: "Caminhante Espiritual", description: "Pode conjurar comunhão com a natureza como ritual, mas apenas para obter o conhecimento de uma área." },
          { level: 14, name: "Harmonia Totêmica", description: "Enquanto em fúria, ganhe um poder poderoso do totêmico (Urso: inimigos a 1,5 m têm desvantagem em ataques contra outros; Águia: voo; Lobo: derrubar como ataque bônus)." },
        ],
      },
    ],
  },

  // ─── BARDO ─────────────────────────────────────────────
  {
    id: "bard",
    name: "Bardo",
    hitDie: 8,
    primaryAbilities: ["charisma"],
    savingThrows: ["dexterity", "charisma"],
    armorProficiencies: ["leves"],
    weaponProficiencies: ["simples", "bestas de mão", "espadas longas", "rapieiras", "espadas curtas"],
    toolProficiencies: ["Três instrumentos musicais à escolha"],
    skillChoices: { choose: 3, from: ["acrobatics", "animalHandling", "arcana", "athletics", "deception", "history", "insight", "intimidation", "investigation", "medicine", "nature", "perception", "performance", "persuasion", "religion", "sleightOfHand", "stealth", "survival"] },
    subclassLevel: 3,
    spellcasting: { type: "full", ability: "charisma", preparation: "known", startsAtLevel: 1, ritualCasting: true },
    startingEquipment: [
      "Rapieira, espada longa ou qualquer arma simples",
      "Pacote de diplomata ou de artista",
      "Alaúde ou outro instrumento",
      "Armadura de couro e adaga",
    ],
    startingGoldDice: "5d4×10",
    features: [
      { level: 1, name: "Conjuração", description: "Você conhece truques e magias da lista de bardo. Carisma é sua habilidade de conjuração. Conjura usando espaços de magia e recupera espaços em descanso longo." },
      { level: 1, name: "Inspiração de Bardo", description: "Como ação bônus, inspire uma criatura a até 18 m. Ela ganha um dado de inspiração (d6) para adicionar a uma jogada de ataque, teste ou salvaguarda em 10 minutos. Usos = modificador de Carisma por descanso longo." },
      { level: 2, name: "Expertisco", description: "Escolha duas perícias proficientes; seu bônus de proficiência é dobrado para testes com elas." },
      { level: 2, name: "Canção de Descanso", description: "Durante um descanso curto, use música para ajudar a recuperar PV: aliados que ouvem e gastam Dados de Vida recuperam PV extras (d6, aumenta com nível)." },
      { level: 3, name: "Colégio de Bardo", description: "Escolha um colégio de bardo que concede características nos níveis 3, 6 e 14." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 5, name: "Fonte de Inspiração", description: "Recupera todos os usos de Inspiração de Bardo ao terminar um descanso curto ou longo. O dado aumenta para d8." },
      { level: 6, name: "Contraencantamento", description: "Como ação, até o fim do seu próximo turno, você e aliados a 9 m têm vantagem em salvaguardas contra ser enfeitiçado ou amedrontado." },
      { level: 6, name: "Característica do Colégio", description: "Você ganha uma característica do seu colégio de bardo." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 10, name: "Expertisco", description: "Escolha mais duas perícias para expertise. Dado de inspiração aumenta para d10." },
      { level: 10, name: "Segredos Mágicos", description: "Aprenda duas magias de qualquer classe (nível que possa conjurar). Contam como magias de bardo." },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 14, name: "Segredos Mágicos", description: "Aprenda mais duas magias de qualquer classe." },
      { level: 14, name: "Característica do Colégio", description: "Você ganha uma característica do seu colégio de bardo." },
      { level: 15, name: "Inspiração de Bardo", description: "Seu dado de Inspiração de Bardo aumenta para d12." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 18, name: "Segredos Mágicos", description: "Aprenda mais duas magias de qualquer classe." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 20, name: "Inspiração Superior", description: "Quando rolar iniciativa e não tiver usos de Inspiração de Bardo, recupera um uso." },
    ],
    subclasses: [
      {
        id: "lore",
        name: "Colégio do Conhecimento",
        description: "Bardos do Colégio do Conhecimento sabem algo sobre a maioria das coisas, coletando bits de conhecimento de fontes espalhadas por todo o multiverso.",
        features: [
          { level: 3, name: "Proficiências Adicionais", description: "Você ganha proficiência em três perícias à sua escolha." },
          { level: 3, name: "Palavras Cortantes", description: "Quando uma criatura a 18 m que você possa ver fizer uma jogada de ataque, teste ou dano, pode usar reação e gastar uma Inspiração de Bardo para subtrair o dado do total da criatura." },
          { level: 6, name: "Segredos Mágicos Adicionais", description: "Aprenda duas magias de qualquer classe (nível que possa conjurar)." },
          { level: 14, name: "Perícia Inigualável", description: "Ao fazer um teste de habilidade e falhar, pode gastar uma Inspiração de Bardo e adicionar o dado ao teste, usando potencialmente um novo resultado." },
        ],
      },
    ],
  },

  // ─── CLÉRIGO ───────────────────────────────────────────
  {
    id: "cleric",
    name: "Clérigo",
    hitDie: 8,
    primaryAbilities: ["wisdom"],
    savingThrows: ["wisdom", "charisma"],
    armorProficiencies: ["leves", "médias", "escudos"],
    weaponProficiencies: ["simples"],
    toolProficiencies: [],
    skillChoices: { choose: 2, from: ["history", "insight", "medicine", "persuasion", "religion"] },
    subclassLevel: 1,
    spellcasting: { type: "full", ability: "wisdom", preparation: "prepared", startsAtLevel: 1, ritualCasting: true },
    startingEquipment: [
      "Maça ou martelo de guerra (se proficiente)",
      "Armadura de escamas, couro ou cota de malha (se proficiente)",
      "Besta leve e 20 virotes ou qualquer arma simples",
      "Pacote de sacerdote e escudo e símbolo sagrado",
    ],
    startingGoldDice: "5d4×10",
    features: [
      { level: 1, name: "Conjuração", description: "Prepare e conjure magias de clérigo. Sabedoria é sua habilidade de conjuração. Pode mudar a lista preparada após um descanso longo." },
      { level: 1, name: "Domínio Divino", description: "Escolha um domínio relacionado à sua divindade. Concede magias de domínio e características." },
      { level: 2, name: "Canalizar Divindade", description: "Pode canalizar energia divina. Expulsar Mortos-Vivos e opção do domínio. Uma vez por descanso curto ou longo (duas no 6º, três no 18º)." },
      { level: 2, name: "Expulsar Mortos-Vivos", description: "Como ação, apresente o símbolo sagrado: cada morto-vivo a 9 m que possa vê-lo/ouvi-lo faz salvaguarda de Sabedoria ou fica expulso por 1 minuto." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 5, name: "Destruir Mortos-Vivos", description: "Quando um morto-vivo falha na salvaguarda contra Expulsar, ele é destruído se o TR for baixo o suficiente (CR 1/2 no 5º, aumenta com nível)." },
      { level: 6, name: "Característica do Domínio", description: "Você ganha uma característica do seu domínio divino." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 8, name: "Característica do Domínio", description: "Impacto Divino ou similar do domínio." },
      { level: 10, name: "Intervenção Divina", description: "Como ação, implore ajuda à sua divindade: role d100; se ≤ nível de clérigo, a divindade intervém. Uma vez por descanso longo; se tiver sucesso, não pode usar novamente por 7 dias." },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 14, name: "Destruir Mortos-Vivos", description: "CR máximo para destruição aumenta." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 17, name: "Característica do Domínio", description: "Você ganha a característica final do seu domínio." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 20, name: "Intervenção Divina", description: "Seu pedido de intervenção tem sucesso automático." },
    ],
    subclasses: [
      {
        id: "life",
        name: "Domínio da Vida",
        description: "O Domínio da Vida foca na energia positiva vibrante que sustenta toda a vida. Clérigos desse domínio são curadores inigualáveis.",
        expandedSpells: { 1: ["bless", "cure-wounds"], 3: ["lesser-restoration", "spiritual-weapon"], 5: ["beacon-of-hope", "revivify"], 7: ["death-ward", "guardian-of-faith"], 9: ["mass-cure-wounds", "raise-dead"] },
        features: [
          { level: 1, name: "Discípulo da Vida", description: "Magias de cura de 1º nível ou superior restauram PV adicionais iguais a 2 + nível da magia." },
          { level: 1, name: "Proficiência Adicional", description: "Você ganha proficiência com armaduras pesadas." },
          { level: 2, name: "Canalizar Divindade: Preservar Vida", description: "Como ação, restaure PV iguais a 5 × nível de clérigo, divididos entre criaturas a 9 m (não podem ultrapassar metade do máximo)." },
          { level: 6, name: "Curandeiro Abençoado", description: "Quando conjurar magia de cura de 1º+ em outras criaturas, você também recupera 2 + nível da magia em PV." },
          { level: 8, name: "Impacto Divino", description: "Uma vez por turno, ataque com arma causa +1d8 radiante; aumenta para 2d8 no 14º nível." },
          { level: 17, name: "Cura Suprema", description: "Ao normalmente rolar um ou mais dados para restaurar PV com magia, use o resultado máximo em cada dado." },
        ],
      },
      {
        id: "light",
        name: "Domínio da Luz",
        description: "Deuses da luz promovem os ideais de renascimento e renovação, verdade, vigilância e beleza, muitas vezes usando o sol como símbolo.",
        expandedSpells: { 1: ["burning-hands", "faerie-fire"], 3: ["flaming-sphere", "scorching-ray"], 5: ["daylight", "fireball"], 7: ["guardian-of-faith", "wall-of-fire"], 9: ["flame-strike", "scrying"] },
        features: [
          { level: 1, name: "Truque Adicional", description: "Você conhece o truque luz." },
          { level: 1, name: "Explosão de Radiância", description: "Quando atacado por criatura visível a 9 m, use reação: o atacante faz salvaguarda de Destreza ou sofre 1d10 radiante (aumenta) e ataque tem desvantagem." },
          { level: 2, name: "Canalizar Divindade: Radiância da Alvorada", description: "Como ação, disperse magia de escuridão a 9 m e cause 2d10 + nível de clérigo de dano radiante (salvaguarda de Constituição pela metade)." },
          { level: 6, name: "Explosão Melhorada", description: "Pode usar Explosão de Radiância um número de vezes igual ao modificador de Sabedoria por descanso longo." },
          { level: 8, name: "Impacto Potente", description: "Adicione modificador de Sabedoria ao dano de qualquer truque de clérigo." },
          { level: 17, name: "Coroa de Luz", description: "Como ação, emane luz solar brilhante em 18 m por 1 minuto: inimigos na luz têm desvantagem em salvaguardas contra suas magias de fogo/radiante." },
        ],
      },
      {
        id: "tempest",
        name: "Domínio da Tempestade",
        description: "Deuses cujo poder está ligado às forças da tempestade governam a tempestade, o mar e o céu.",
        expandedSpells: { 1: ["fog-cloud", "thunderwave"], 3: ["gust-of-wind", "shatter"], 5: ["call-lightning", "sleet-storm"], 7: ["control-water", "ice-storm"], 9: ["destructive-wave", "insect-plague"] },
        features: [
          { level: 1, name: "Proficiências Adicionais", description: "Proficiência com armas marciais e armaduras pesadas." },
          { level: 1, name: "Fúria da Tempestade", description: "Quando acertado por ataque corpo a corpo a 1,5 m, use reação: atacante faz salvaguarda de Destreza ou sofre 2d8 relâmpago/trovão (metade em sucesso). Usos = modificador de Sabedoria." },
          { level: 2, name: "Canalizar Divindade: Ira Destrutiva", description: "Quando rolar dano de relâmpago ou trovão, pode tratar os resultados dos dados como máximo." },
          { level: 6, name: "Golpe de Trovão", description: "Quando causar dano de relâmpago a criatura Grande ou menor, pode empurrá-la até 3 m." },
          { level: 8, name: "Impacto Divino", description: "Uma vez por turno, +1d8 trovão em ataque com arma; 2d8 no 14º." },
          { level: 17, name: "Filho da Tempestade", description: "Voo com deslocamento igual ao caminhada enquanto não estiver underground ou indoor." },
        ],
      },
      {
        id: "nature",
        name: "Domínio da Natureza",
        description: "Deuses da natureza são tão variados quanto as próprias terras naturais, desde deuses das florestas profundas até deuses das fontes e riachos.",
        expandedSpells: { 1: ["animal-friendship", "speak-with-animals"], 3: ["barkskin", "spike-growth"], 5: ["plant-growth", "wind-wall"], 7: ["dominate-beast", "grasping-vine"], 9: ["insect-plague", "tree-stride"] },
        features: [
          { level: 1, name: "Discípulo da Natureza", description: "Aprenda um truque de druida e ganhe proficiência em uma perícia: Lidar com Animais, Natureza ou Sobrevivência." },
          { level: 1, name: "Proficiência Adicional", description: "Proficiência com armaduras pesadas." },
          { level: 2, name: "Canalizar Divindade: Encantar Animais e Plantas", description: "Como ação, cada fera ou planta a 9 m faz salvaguarda de Sabedoria ou fica enfeitiçada por 1 minuto." },
          { level: 6, name: "Amortecer Elementos", description: "Quando você ou criatura a 9 m sofrer dano de ácido, frio, fogo, relâmpago ou trovão, use reação para conceder resistência a esse dano." },
          { level: 8, name: "Impacto Divino", description: "Uma vez por turno, +1d8 frio/fogo/relâmpago em ataque com arma; 2d8 no 14º." },
          { level: 17, name: "Mestre da Natureza", description: "Enquanto criaturas estão enfeitiçadas por Encantar Animais e Plantas, pode usar ação bônus para comandá-las verbalmente." },
        ],
      },
      {
        id: "knowledge",
        name: "Domínio do Conhecimento",
        description: "Os deuses do conhecimento valorizam aprendizado e compreensão acima de tudo.",
        expandedSpells: { 1: ["command", "identify"], 3: ["augury", "suggestion"], 5: ["nondetection", "speak-with-dead"], 7: ["arcane-eye", "confusion"], 9: ["legend-lore", "scrying"] },
        features: [
          { level: 1, name: "Bênçãos do Conhecimento", description: "Aprenda dois idiomas. Ganhe expertise em duas perícias: Arcana, História, Natureza ou Religião." },
          { level: 2, name: "Canalizar Divindade: Conhecimento das Eras", description: "Como ação, escolha uma perícia ou ferramenta: por 10 minutos, tem proficiência com ela." },
          { level: 6, name: "Canalizar Divindade: Ler Pensamentos", description: "Como ação, escolha criatura a 18 m: leia pensamentos superficiais (salvaguarda de Sabedoria). Pode então conjurar sugestão sem espaço." },
          { level: 8, name: "Impacto Potente", description: "Adicione modificador de Sabedoria ao dano de truques de clérigo." },
          { level: 17, name: "Visões do Passado", description: "Após meditar, chame visões ligadas a objeto que segura ou área onde está (detalhes conforme PHB)." },
        ],
      },
      {
        id: "war",
        name: "Domínio da Guerra",
        description: "Deuses da guerra vigiam guerreiros em todas as formas, desde soldados honoráveis até bárbaros sanguinários.",
        expandedSpells: { 1: ["divine-favor", "shield-of-faith"], 3: ["magic-weapon", "spiritual-weapon"], 5: ["crusaders-mantle", "spirit-guardians"], 7: ["freedom-of-movement", "stoneskin"], 9: ["flame-strike", "hold-monster"] },
        features: [
          { level: 1, name: "Proficiências Adicionais", description: "Proficiência com armas marciais e armaduras pesadas." },
          { level: 1, name: "Sacerdote de Guerra", description: "Quando tomar a ação Ataque, pode fazer um ataque com arma como ação bônus. Usos = modificador de Sabedoria por descanso longo." },
          { level: 2, name: "Canalizar Divindade: Golpe Guiado", description: "Ao fazer jogada de ataque, pode usar Canalizar Divindade para obter +10 na jogada (após ver o resultado)." },
          { level: 6, name: "Canalizar Divindade: Bênção do Deus da Guerra", description: "Quando criatura a 9 m fizer jogada de ataque, use reação para conceder +10 na jogada." },
          { level: 8, name: "Impacto Divino", description: "Uma vez por turno, +1d8 no ataque com arma; 2d8 no 14º." },
          { level: 17, name: "Avatar de Batalha", description: "Resistência a dano de concussão, perfurante e cortante de armas não mágicas." },
        ],
      },
      {
        id: "trickery",
        name: "Domínio da Trapaça",
        description: "Deuses da trapaça são trapaceiros e instigadores que se erguem contra a opressão e se divertem às custas dos poderosos.",
        expandedSpells: { 1: ["charm-person", "disguise-self"], 3: ["mirror-image", "pass-without-trace"], 5: ["blink", "dispel-magic"], 7: ["dimension-door", "polymorph"], 9: ["dominate-person", "modify-memory"] },
        features: [
          { level: 1, name: "Bênção do Trapaceiro", description: "Como ação, toque criatura voluntária (não você): por 1 hora, ela tem vantagem em Destreza (Furtividade). Concentração; uma criatura por vez." },
          { level: 2, name: "Canalizar Divindade: Invocar Dualidade", description: "Crie uma ilusão perfeita de si a até 9 m. Pode mover a ilusão 9 m e conjurar como se estivesse no espaço dela." },
          { level: 6, name: "Canalizar Divindade: Manto das Sombras", description: "Como ação, torne-se invisível até o fim do seu próximo turno. Termina se atacar ou conjurar." },
          { level: 8, name: "Impacto Divino", description: "Uma vez por turno, +1d8 veneno em ataque com arma; 2d8 no 14º." },
          { level: 17, name: "Duplicata Melhorada", description: "Pode criar até quatro duplicatas com Invocar Dualidade; pode mover qualquer número com 36 m totais de movimento." },
        ],
      },
    ],
  },

  // ─── DRUIDA ────────────────────────────────────────────
  {
    id: "druid",
    name: "Druida",
    hitDie: 8,
    primaryAbilities: ["wisdom"],
    savingThrows: ["intelligence", "wisdom"],
    armorProficiencies: ["leves", "médias", "escudos (não de metal)"],
    weaponProficiencies: ["clavas", "adagas", "dardos", "azagaias", "maças", "cajados", "cimitarras", "foices", "fundas", "lanças"],
    toolProficiencies: ["Kit de herbalismo"],
    skillChoices: { choose: 2, from: ["arcana", "animalHandling", "insight", "medicine", "nature", "perception", "religion", "survival"] },
    subclassLevel: 2,
    spellcasting: { type: "full", ability: "wisdom", preparation: "prepared", startsAtLevel: 1, ritualCasting: true },
    startingEquipment: [
      "Escudo de madeira ou qualquer arma simples",
      "Cimitarra ou qualquer arma corpo a corpo simples",
      "Pacote de estudioso ou de explorador",
      "Armadura de couro, pacote de explorador e foco druídico",
    ],
    startingGoldDice: "2d4×10",
    features: [
      { level: 1, name: "Druídico", description: "Você conhece o Druídico, a linguagem secreta dos druidas." },
      { level: 1, name: "Conjuração", description: "Prepare e conjure magias de druida. Sabedoria é sua habilidade de conjuração." },
      { level: 2, name: "Forma Selvagem", description: "Como ação, assume a forma de uma fera que já viu. Limitações de CR e voo/natação conforme nível. Usa estatísticas da fera, mantém alinhamento, personalidade, Int/Sab/Car e PV separados." },
      { level: 2, name: "Círculo Druídico", description: "Escolha um círculo que concede características." },
      { level: 4, name: "Forma Selvagem Melhorada", description: "Pode transformar-se em feras de CR 1/2 (sem voo)." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 8, name: "Forma Selvagem Melhorada", description: "Pode transformar-se em feras de CR 1." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 18, name: "Corpo Atemporal", description: "A magia do primal faz você envelhecer mais lentamente: a cada 10 anos, seu corpo envelhece apenas 1 ano." },
      { level: 18, name: "Magias de Fera", description: "Pode realizar componentes somáticos e verbais de magias de druida enquanto em Forma Selvagem." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 20, name: "Arquidruida", description: "Pode usar Forma Selvagem um número ilimitado de vezes. Ignora componentes verbais, somáticos e materiais sem custo de magias de druida." },
    ],
    subclasses: [
      {
        id: "land",
        name: "Círculo da Terra",
        description: "Os mistagogos do Círculo da Terra são os guardiões do conhecimento antigo e das tradições dos druidas.",
        features: [
          { level: 2, name: "Companheiro Bonus", description: "Você aprende um truque de druida adicional." },
          { level: 2, name: "Recuperação Natural", description: "Durante um descanso curto, recupere espaços de magia com nível total igual a metade do nível de druida (arredondado para cima). Uma vez por descanso longo." },
          { level: 3, name: "Magias do Círculo", description: "Escolha um terreno (ártico, costa, deserto, floresta, pradaria, montanha, pântano, Submundo). Ganhe magias sempre preparadas conforme o terreno e nível." },
          { level: 6, name: "Passo da Terra", description: "Mover-se através de terreno difícil não-mágico não custa movimento extra. Tem vantagem em salvaguardas contra plantas magicamente criadas ou manipuladas." },
          { level: 10, name: "Proteção da Natureza", description: "Não pode ser enfeitiçado ou amedrontado por elementais ou fadas, e imune a veneno e doença." },
          { level: 14, name: "Santuário da Natureza", description: "Feras e plantas têm dificuldade em atacá-lo: devem fazer salvaguarda de Sabedoria ou escolher outro alvo." },
        ],
      },
      {
        id: "moon",
        name: "Círculo da Lua",
        description: "Druidas do Círculo da Lua são ferozes guardiões da natureza selvagem. Sua Forma Selvagem é particularmente poderosa.",
        features: [
          { level: 2, name: "Forma Selvagem de Combate", description: "Pode usar Forma Selvagem como ação bônus. Pode transformar-se em feras de CR 1." },
          { level: 2, name: "Formas Circulares", description: "CR máximo de Forma Selvagem = nível de druida ÷ 3 (arredondado para baixo) a partir do 6º." },
          { level: 6, name: "Golpe Primal", description: "Ataques em Forma Selvagem contam como mágicos para superar resistência/imunidade." },
          { level: 10, name: "Formas Elementais", description: "Pode gastar dois usos de Forma Selvagem para transformar-se em elemental de ar, terra, fogo ou água." },
          { level: 14, name: "Mil Formas", description: "Pode conjurar alterar-se à vontade." },
        ],
      },
    ],
  },

  // ─── GUERREIRO ─────────────────────────────────────────
  {
    id: "fighter",
    name: "Guerreiro",
    hitDie: 10,
    primaryAbilities: ["strength", "dexterity"],
    savingThrows: ["strength", "constitution"],
    armorProficiencies: ["todas as armaduras", "escudos"],
    weaponProficiencies: ["simples", "marciais"],
    toolProficiencies: [],
    skillChoices: { choose: 2, from: ["acrobatics", "animalHandling", "athletics", "history", "insight", "intimidation", "perception", "survival"] },
    subclassLevel: 3,
    spellcasting: noSpellcasting,
    startingEquipment: [
      "Cota de malha ou armadura de couro, arco longo e 20 flechas",
      "Arma marcial e escudo, ou duas armas marciais",
      "Besta leve e 20 virotes ou duas machadinhas",
      "Pacote de dungeoneer ou de explorador",
    ],
    startingGoldDice: "5d4×10",
    features: [
      { level: 1, name: "Estilo de Combate", description: "Adote um estilo de combate: Arquearia, Defesa, Duelo, Combate com Arma Grande, Proteção ou Combate com Duas Armas." },
      { level: 1, name: "Segundo Fôlego", description: "Como ação bônus, recupere 1d10 + nível de guerreiro em PV. Uma vez por descanso curto ou longo." },
      { level: 2, name: "Surto de Ação", description: "Em seu turno, tome uma ação adicional. Uma vez por descanso curto ou longo. (Dois usos no 17º.)" },
      { level: 3, name: "Arquétipo Marcial", description: "Escolha um arquétipo que molda seu estilo de combate." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 5, name: "Ataque Extra", description: "Pode atacar duas vezes com a ação Ataque. (Três no 11º, quatro no 20º.)" },
      { level: 6, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 7, name: "Característica do Arquétipo", description: "Você ganha uma característica do seu arquétipo." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 9, name: "Indomável", description: "Pode rerrolar uma salvaguarda que falhou. Deve usar o novo resultado. Uma vez por descanso longo (mais usos em níveis altos)." },
      { level: 10, name: "Característica do Arquétipo", description: "Você ganha uma característica do seu arquétipo." },
      { level: 11, name: "Ataque Extra", description: "Pode atacar três vezes com a ação Ataque." },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 13, name: "Indomável", description: "Pode usar Indomável duas vezes por descanso longo." },
      { level: 14, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 15, name: "Característica do Arquétipo", description: "Você ganha uma característica do seu arquétipo." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 17, name: "Surto de Ação", description: "Pode usar Surto de Ação duas vezes por descanso, mas apenas uma vez por turno." },
      { level: 17, name: "Indomável", description: "Pode usar Indomável três vezes por descanso longo." },
      { level: 18, name: "Característica do Arquétipo", description: "Você ganha uma característica do seu arquétipo." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 20, name: "Ataque Extra", description: "Pode atacar quatro vezes com a ação Ataque." },
    ],
    subclasses: [
      {
        id: "champion",
        name: "Campeão",
        description: "O arquétipo Campeão foca no desenvolvimento de poder físico bruto em combate mortal.",
        features: [
          { level: 3, name: "Crítico Melhorado", description: "Seus ataques com arma criticam em 19–20. (18–20 no 15º.)" },
          { level: 7, name: "Atleta Remarkável", description: "Adicione metade do bônus de proficiência (arredondado para cima) a qualquer teste de Força, Destreza ou Constituição em que não seja proficiente. Corrida de salto aumentada." },
          { level: 10, name: "Estilo de Combate Adicional", description: "Escolha um segundo estilo de combate." },
          { level: 15, name: "Crítico Superior", description: "Seus ataques com arma criticam em 18–20." },
          { level: 18, name: "Sobrevivente", description: "No início de cada turno, se tiver ≤ metade dos PV e ≥ 1 PV, recupera 5 + modificador de Constituição em PV." },
        ],
      },
      {
        id: "battle-master",
        name: "Mestre de Batalha",
        description: "Mestres de Batalha empregam técnicas marciais transmitidas através de gerações, usando manobras especiais em combate.",
        features: [
          { level: 3, name: "Superioridade de Combate", description: "Aprende manobras alimentadas por dados de superioridade (d8). Quatro dados; recupera em descanso curto ou longo. CD = 8 + proficiência + Força ou Destreza." },
          { level: 3, name: "Estudante de Guerra", description: "Ganha proficiência com um tipo de ferramentas de artesão." },
          { level: 7, name: "Conheça Seu Inimigo", description: "Se gastar 1 minuto fora de combate observando criatura, aprende certas informações (comparação de atributos, armadura, níveis de classe etc.)." },
          { level: 10, name: "Melhoria de Superioridade de Combate", description: "Dados de superioridade passam a ser d10. Aprende mais manobras." },
          { level: 15, name: "Relâmpago Relativo", description: "Quando rolar iniciativa e não tiver dados de superioridade, recupera um." },
          { level: 18, name: "Melhoria de Superioridade de Combate", description: "Dados de superioridade passam a ser d12." },
        ],
      },
      {
        id: "eldritch-knight",
        name: "Cavaleiro Arcano",
        description: "O Cavaleiro Arcano combina a maestria marcial do guerreiro com um estudo cuidadoso da magia.",
        features: [
          { level: 3, name: "Conjuração", description: "Aprende truques e magias de mago (abjuração e evocação principalmente). Inteligência é a habilidade de conjuração. Conjuração de um terço." },
          { level: 3, name: "Vínculo com Arma", description: "Pode vincular-se a até duas armas. Não pode ser desarmado delas a menos que esteja incapacitado. Pode teletransportar uma arma vinculada para a mão como ação bônus." },
          { level: 7, name: "Ataque de Guerra", description: "Quando usar ação para conjurar magia, pode fazer um ataque com arma como ação bônus." },
          { level: 10, name: "Golpe Arcano", description: "Ao acertar criatura com ataque com arma, ela tem desvantagem na próxima salvaguarda contra uma magia sua antes do fim do seu próximo turno." },
          { level: 15, name: "Carga Arcana", description: "Quando usar Surto de Ação, pode teletransportar-se até 9 m para um espaço desocupado que possa ver." },
          { level: 18, name: "Ataque de Guerra Melhorado", description: "Quando tomar a ação Ataque, pode substituir um ataque por conjurar um truque." },
        ],
      },
    ],
  },

  // ─── MONGE ─────────────────────────────────────────────
  {
    id: "monk",
    name: "Monge",
    hitDie: 8,
    primaryAbilities: ["dexterity", "wisdom"],
    savingThrows: ["strength", "dexterity"],
    armorProficiencies: [],
    weaponProficiencies: ["simples", "espadas curtas"],
    toolProficiencies: ["Um tipo de ferramentas de artesão ou um instrumento musical"],
    skillChoices: { choose: 2, from: ["acrobatics", "athletics", "history", "insight", "religion", "stealth"] },
    subclassLevel: 3,
    spellcasting: noSpellcasting,
    startingEquipment: [
      "Espada curta ou qualquer arma simples",
      "Pacote de dungeoneer ou de explorador",
      "10 dardos",
    ],
    startingGoldDice: "5d4",
    features: [
      { level: 1, name: "Defesa sem Armadura", description: "Enquanto não usar armadura nem escudo, CA = 10 + Destreza + Sabedoria." },
      { level: 1, name: "Artes Marciais", description: "Com ataques desarmados ou armas de monge: pode usar Destreza; dano é dado de artes marciais; pode atacar desarmado como ação bônus após ataque." },
      { level: 2, name: "Ki", description: "Possui pontos de ki iguais ao nível de monge. Alimentam características especiais. CD = 8 + proficiência + Sabedoria. Recupera em descanso curto ou longo." },
      { level: 2, name: "Movimento sem Armadura", description: "Deslocamento aumenta em 3 m (mais em níveis altos) enquanto sem armadura/escudo." },
      { level: 3, name: "Tradição Monástica", description: "Escolha uma tradição monástica." },
      { level: 3, name: "Defletir Mísseis", description: "Como reação, reduza dano de ataque à distância em 1d10 + Destreza + nível. Se reduzir a 0 e for munição, pode gastar 1 ki para arremessar de volta." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 4, name: "Queda Lenta", description: "Como reação ao cair, reduza dano de queda em 5 × nível de monge." },
      { level: 5, name: "Ataque Extra", description: "Pode atacar duas vezes com a ação Ataque." },
      { level: 5, name: "Golpe Atordoante", description: "Ao acertar com ataque corpo a corpo, gaste 1 ki: alvo faz salvaguarda de Constituição ou fica atordoado até o fim do seu próximo turno." },
      { level: 6, name: "Golpes Potenciados por Ki", description: "Ataques desarmados contam como mágicos." },
      { level: 6, name: "Característica da Tradição", description: "Você ganha uma característica da sua tradição." },
      { level: 7, name: "Evasão", description: "Em salvaguardas de Destreza para metade do dano: nenhum dano em sucesso, metade em falha." },
      { level: 7, name: "Quietude da Mente", description: "Como ação, termina um efeito que o está enfeitiçando ou amedrontando." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 10, name: "Pureza Corporal", description: "Imunidade a doença e veneno." },
      { level: 11, name: "Característica da Tradição", description: "Você ganha uma característica da sua tradição." },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 13, name: "Língua do Sol e da Lua", description: "Entende todos os idiomas e qualquer criatura que saiba um idioma pode entendê-lo." },
      { level: 14, name: "Diamante da Alma", description: "Proficiência em todas as salvaguardas. Pode gastar 1 ki para rerrolar uma salvaguarda falha." },
      { level: 15, name: "Corpo Atemporal", description: "Não sofre as fragilidades da velhice e não pode ser envelhecido magicamente. Não precisa de comida nem água." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 17, name: "Característica da Tradição", description: "Você ganha uma característica da sua tradição." },
      { level: 18, name: "Corpo Vazio", description: "Como ação, gaste 4 ki para ficar invisível por 1 minuto e resistente a todos os danos exceto força. Ou gaste 8 ki para conjurar projeção astral." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 20, name: "Perfeição", description: "Quando rolar iniciativa e tiver 0 ki, recupera 4 pontos de ki." },
    ],
    subclasses: [
      {
        id: "open-hand",
        name: "Caminho da Mão Aberta",
        description: "Monges da Mão Aberta são mestres absolutos das artes marciais, usando empurrões, derrubadas e técnicas que incapacitan.",
        features: [
          { level: 3, name: "Técnica da Mão Aberta", description: "Quando acertar com Rajada de Golpes, imponha um efeito: derrubar (salvaguarda de Destreza), empurrar 4,5 m (Força) ou impedir reações até o fim do próximo turno." },
          { level: 6, name: "Integridade Corporal", description: "Como ação, recupere PV iguais a 3 × nível de monge. Uma vez por descanso longo." },
          { level: 11, name: "Tranquilidade", description: "Ao terminar um descanso longo, ganhe o efeito de santuário (CD = ki) até o próximo descanso longo." },
          { level: 17, name: "Palma Vibrante", description: "Ao acertar com ataque desarmado, gaste 3 ki para iniciar vibrações letais. Em 1d até número de dias = nível, pode usar ação para forçar salvaguarda de Constituição: em falha, 0 PV; em sucesso, 10d10 necrótico." },
        ],
      },
      {
        id: "shadow",
        name: "Caminho da Sombra",
        description: "Monges do Caminho da Sombra seguem a tradição do ninja, mestres do furtivo e da subterfúgio.",
        features: [
          { level: 3, name: "Artes das Sombras", description: "Pode gastar 2 ki para conjurar escuridão, visão no escuro, passagem sem rastros ou silêncio (sem material)." },
          { level: 6, name: "Passo das Sombras", description: "Quando estiver em área de penumbra ou escuridão, como ação bônus gaste 2 ki para se teletransportar até 18 m para espaço similar; ganha vantagem no próximo ataque corpo a corpo antes do fim do turno." },
          { level: 11, name: "Manto das Sombras", description: "Quando em área de penumbra ou escuridão, use ação para ficar invisível até atacar, conjurar ou entrar em luz plena." },
          { level: 17, name: "Oportunista", description: "Quando criatura a 1,5 m for acertada por ataque de outra que não você, use reação para fazer ataque corpo a corpo contra ela." },
        ],
      },
      {
        id: "four-elements",
        name: "Caminho dos Quatro Elementos",
        description: "Você segue uma tradição monástica que ensina a aproveitar os elementos, moldando ki em magias elementais.",
        features: [
          { level: 3, name: "Discípulo dos Elementos", description: "Aprende disciplinas elementais. Pode gastar ki para conjurar efeitos como garras de fogo, moldar a água, golpe de vento etc. Aprende mais em níveis altos." },
          { level: 6, name: "Disciplina Adicional", description: "Aprende mais uma disciplina elemental." },
          { level: 11, name: "Disciplina Adicional", description: "Aprende mais uma disciplina elemental." },
          { level: 17, name: "Disciplina Adicional", description: "Aprende mais uma disciplina elemental." },
        ],
      },
    ],
  },

  // ─── PALADINO ──────────────────────────────────────────
  {
    id: "paladin",
    name: "Paladino",
    hitDie: 10,
    primaryAbilities: ["strength", "charisma"],
    savingThrows: ["wisdom", "charisma"],
    armorProficiencies: ["todas as armaduras", "escudos"],
    weaponProficiencies: ["simples", "marciais"],
    toolProficiencies: [],
    skillChoices: { choose: 2, from: ["athletics", "insight", "intimidation", "medicine", "persuasion", "religion"] },
    subclassLevel: 3,
    spellcasting: { type: "half", ability: "charisma", preparation: "prepared", startsAtLevel: 2 },
    startingEquipment: [
      "Arma marcial e escudo, ou duas armas marciais",
      "Cinco azagaias ou qualquer arma corpo a corpo simples",
      "Pacote de sacerdote ou de explorador",
      "Cota de malha e símbolo sagrado",
    ],
    startingGoldDice: "5d4×10",
    features: [
      { level: 1, name: "Sentido Divino", description: "Como ação, até o fim do próximo turno, conhece localização de qualquer celestial, demônio ou morto-vivo a 18 m não atrás de cobertura total. Também detecta locais e objetos consagrados ou profanos. Usos = 1 + Carisma por descanso longo." },
      { level: 1, name: "Impor as Mãos", description: "Poço de cura = 5 × nível de paladino. Como ação, toque criatura e restaure PV gastando do poço. Alternativamente, gaste 5 PV do poço para curar uma doença ou neutralizar um veneno. Recupera em descanso longo." },
      { level: 2, name: "Estilo de Combate", description: "Escolha Defesa, Duelo, Combate com Arma Grande ou Proteção." },
      { level: 2, name: "Conjuração", description: "Prepare e conjure magias de paladino. Carisma é a habilidade de conjuração. Conjuração parcial." },
      { level: 2, name: "Golpe Divino", description: "Ao acertar com ataque corpo a corpo com arma, pode gastar um espaço de magia para causar +2d8 radiante (+1d8 por nível acima do 1º, máx +5d8; +1d8 vs mortos-vivos/demônios)." },
      { level: 3, name: "Saúde Divina", description: "Imunidade a doenças." },
      { level: 3, name: "Juramento Sagrado", description: "Faça o juramento que concede Canalizar Divindade e características." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 5, name: "Ataque Extra", description: "Pode atacar duas vezes com a ação Ataque." },
      { level: 6, name: "Aura de Proteção", description: "Você e aliados amigáveis a 3 m (9 m no 18º) adicionam seu modificador de Carisma a salvaguardas enquanto estiver consciente." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 10, name: "Aura de Coragem", description: "Você e aliados a 3 m (9 m no 18º) não podem ser amedrontados enquanto estiver consciente." },
      { level: 11, name: "Golpe Divino Aprimorado", description: "Todos os ataques corpo a corpo com arma causam +1d8 radiante." },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 14, name: "Toque Purificador", description: "Como ação, termine uma magia em si ou em criatura voluntária tocada. Usos = modificador de Carisma por descanso longo." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 18, name: "Auras Melhoradas", description: "Alcance das auras aumenta para 9 m." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 20, name: "Característica do Juramento", description: "Você ganha a característica final do seu juramento." },
    ],
    subclasses: [
      {
        id: "devotion",
        name: "Juramento de Devoção",
        description: "O Juramento de Devoção vincula o paladino aos mais altos ideais de justiça, virtude e ordem — os cavaleiros brancos clássicos.",
        expandedSpells: { 3: ["protection-from-evil-and-good", "sanctuary"], 5: ["lesser-restoration", "zone-of-truth"], 9: ["beacon-of-hope", "dispel-magic"], 13: ["freedom-of-movement", "guardian-of-faith"], 17: ["commune", "flame-strike"] },
        features: [
          { level: 3, name: "Canalizar Divindade: Arma Sagrada", description: "Como ação, imbua uma arma: por 1 minuto emana luz e adiciona modificador de Carisma às jogadas de ataque. Conta como mágica." },
          { level: 3, name: "Canalizar Divindade: Expulsar o Ímpio", description: "Como ação, cada demônio ou morto-vivo a 9 m faz salvaguarda de Sabedoria ou fica expulso por 1 minuto." },
          { level: 7, name: "Aura de Devoção", description: "Você e aliados a 3 m (9 m no 18º) não podem ser enfeitiçados enquanto estiver consciente." },
          { level: 15, name: "Pureza do Espírito", description: "Sempre sob o efeito de proteção contra o bem e o mal." },
          { level: 20, name: "Nimbus Sagrado", description: "Como ação, por 1 minuto emane luz solar em 9 m: inimigos que iniciem turno na luz sofrem 10 radiante; vantagem em salvaguardas contra magias de demônios/mortos-vivos." },
        ],
      },
      {
        id: "ancients",
        name: "Juramento dos Antigos",
        description: "O Juramento dos Antigos é tão antigo quanto a raça élfica e dos deuses da natureza. Paladinos deste juramento protegem a luz e a vida contra a decadência.",
        expandedSpells: { 3: ["ensnaring-strike", "speak-with-animals"], 5: ["moonbeam", "misty-step"], 9: ["plant-growth", "protection-from-energy"], 13: ["ice-storm", "stoneskin"], 17: ["commune-with-nature", "tree-stride"] },
        features: [
          { level: 3, name: "Canalizar Divindade: Ira da Natureza", description: "Como ação, espectros de natureza restringem demônios/fadas a 3 m: salvaguarda de Força ou ficam restringidos." },
          { level: 3, name: "Canalizar Divindade: Expulsar Encantados", description: "Como ação, cada demônio ou fada a 9 m faz salvaguarda de Sabedoria ou fica expulso." },
          { level: 7, name: "Aura de Proteção", description: "Você e aliados a 3 m (9 m no 18º) têm resistência a dano de magias." },
          { level: 15, name: "Sentinela Indormiente", description: "Vantagem em salvaguardas de Constituição para manter concentração. Não precisa dormir; não pode ser forçado a dormir magicamente." },
          { level: 20, name: "Campeão Ancião", description: "Como ação, transforme-se por 1 minuto: regenere 10 PV no início do turno; conjure magias de paladino como ação bônus; inimigos a 3 m têm desvantagem em salvaguardas contra suas magias e Canalizar Divindade." },
        ],
      },
      {
        id: "vengeance",
        name: "Juramento de Vingança",
        description: "O Juramento de Vingança é um compromisso solene de punir aqueles que cometeram gravíssimas injustiças.",
        expandedSpells: { 3: ["bane", "hunters-mark"], 5: ["hold-person", "misty-step"], 9: ["haste", "protection-from-energy"], 13: ["banishment", "dimension-door"], 17: ["hold-monster", "scrying"] },
        features: [
          { level: 3, name: "Canalizar Divindade: Abjurar Inimigo", description: "Como ação, uma criatura a 18 m faz salvaguarda de Sabedoria (vantagem se CR ≥ nível) ou fica amedrontada e deslocamento 0 por 1 minuto." },
          { level: 3, name: "Canalizar Divindade: Voto de Inimizade", description: "Como ação bônus, escolha criatura a 18 m: vantagem em ataques contra ela por 1 minuto." },
          { level: 7, name: "Vingador Implacável", description: "Quando acertar criatura com ataque de oportunidade, pode se mover até metade do deslocamento como parte da mesma reação (não provoca)." },
          { level: 15, name: "Alma da Vingança", description: "Quando criatura sob Voto de Inimizade fizer ataque, use reação para fazer ataque corpo a corpo contra ela se estiver ao alcance." },
          { level: 20, name: "Anjo da Vingança", description: "Como ação, transforme-se por 1 hora: asas (voo 18 m); aura de medo 9 m; Voto de Inimizade em qualquer número de criaturas." },
        ],
      },
    ],
  },

  // ─── RANGER ────────────────────────────────────────────
  {
    id: "ranger",
    name: "Patrulheiro",
    hitDie: 10,
    primaryAbilities: ["dexterity", "wisdom"],
    savingThrows: ["strength", "dexterity"],
    armorProficiencies: ["leves", "médias", "escudos"],
    weaponProficiencies: ["simples", "marciais"],
    toolProficiencies: [],
    skillChoices: { choose: 3, from: ["animalHandling", "athletics", "insight", "investigation", "nature", "perception", "stealth", "survival"] },
    subclassLevel: 3,
    spellcasting: { type: "half", ability: "wisdom", preparation: "known", startsAtLevel: 2 },
    startingEquipment: [
      "Armadura de escamas ou de couro",
      "Duas espadas curtas ou duas armas corpo a corpo simples",
      "Pacote de dungeoneer ou de explorador",
      "Arco longo e aljava com 20 flechas",
    ],
    startingGoldDice: "5d4×10",
    features: [
      { level: 1, name: "Inimigo Favorito", description: "Escolha um tipo de inimigo favorito. Tem vantagem em testes de Sabedoria (Sobrevivência) para rastreá-los e de Inteligência para recordá-los. Aprende um idioma deles. Escolha tipos adicionais nos níveis 6 e 14." },
      { level: 1, name: "Explorador Natural", description: "Escolha um terreno favorito. Em terreno favorito: vantagens de viagem, rastreamento, furtividade do grupo etc. Terrenos adicionais nos níveis 6 e 10." },
      { level: 2, name: "Estilo de Combate", description: "Escolha Arquearia, Defesa, Duelo ou Combate com Duas Armas." },
      { level: 2, name: "Conjuração", description: "Conhece e conjura magias de patrulheiro. Sabedoria é a habilidade. Conjuração parcial." },
      { level: 3, name: "Arquétipo de Patrulheiro", description: "Escolha um arquétipo." },
      { level: 3, name: "Sentidos Primais", description: "Pode usar ação e espaço de magia de patrulheiro para focar sentidos por 1 minuto por nível do espaço: sente a presença de certos tipos de criaturas a 1,6 km (ou 9 km no terreno favorito)." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 5, name: "Ataque Extra", description: "Pode atacar duas vezes com a ação Ataque." },
      { level: 6, name: "Inimigo Favorito / Explorador Natural", description: "Escolha um tipo adicional de inimigo e um terreno favorito adicional." },
      { level: 7, name: "Característica do Arquétipo", description: "Você ganha uma característica do seu arquétipo." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 8, name: "Passo da Terra", description: "Mover-se através de terreno difícil não-mágico não custa movimento extra. Pode atravessar vegetação sem ser dificultado. Tem vantagem em salvaguardas contra plantas mágicas." },
      { level: 10, name: "Esconder-se à Vista Plena", description: "Pode gastar 1 minuto criando camuflagem: fica camuflado, tem +10 em Furtividade se permanecer parado sem ações. Terreno favorito adicional." },
      { level: 11, name: "Característica do Arquétipo", description: "Você ganha uma característica do seu arquétipo." },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 14, name: "Desaparecer", description: "Pode usar a ação Esconder-se como ação bônus. Não pode ser rastreado por meios não mágicos a menos que queira." },
      { level: 14, name: "Inimigo Favorito", description: "Escolha um tipo adicional de inimigo favorito." },
      { level: 15, name: "Característica do Arquétipo", description: "Você ganha uma característica do seu arquétipo." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 18, name: "Sentidos Selvagens", description: "A até 9 m, pode sentir a localização de qualquer criatura invisível ou escondida que não esteja atrás de cobertura total." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 20, name: "Matador de Inimigos", description: "Uma vez por turno, adicione modificador de Sabedoria à jogada de ataque ou dano contra inimigo favorito." },
    ],
    subclasses: [
      {
        id: "hunter",
        name: "Caçador",
        description: "Emulando o Arquétipo do Caçador, você aceita seu lugar como baluarte entre a civilização e os terrores da natureza.",
        features: [
          { level: 3, name: "Presa do Caçador", description: "Escolha uma característica: Matador de Colossos (+1d8 se alvo estiver abaixo do máximo de PV), Matador de Hordas (ataque extra vs criatura a 1,5 m diferente) ou Matador Gigante (reação para atacar quando Grande+ te atacar e errar)." },
          { level: 7, name: "Táticas Defensivas", description: "Escolha: Escapar da Horda (desvantagem em ataques de oportunidade contra você), Defesa Multiattaque (desvantagem em ataques subsequentes no turno após um acerto) ou Vontade de Aço (vantagem vs amedrontado)." },
          { level: 11, name: "Multiattaque", description: "Escolha: Rajada (ataque à distância vs qualquer número a 3 m de um ponto) ou Redemoinho (ataque corpo a corpo vs qualquer número a 1,5 m)." },
          { level: 15, name: "Defesa Superior do Caçador", description: "Escolha: Evasão, Esquiva Sobrenatural (reação para metade do dano de ataque) ou Resistência Impenetrável (reduza dano sofrido com resistência quando tiver resistência)." },
        ],
      },
      {
        id: "beast-master",
        name: "Mestre das Feras",
        description: "O Arquétipo do Mestre das Feras incorpora uma amizade entre a natureza civilizada e a selvageria das feras.",
        features: [
          { level: 3, name: "Companheiro Animal", description: "Ganhe um companheiro fera de CR 1/4 ou inferior (sem voo). Age independentemente, mas obedece a comandos. Usa seu bônus de proficiência. Quando toma a ação Ataque, o companheiro pode atacar." },
          { level: 7, name: "Treinamento Excepcional", description: "Em qualquer dos seus turnos em que o companheiro não ataque, pode usar ação bônus para comandá-lo a tomar a ação Disparada, Desengajar ou Ajudar." },
          { level: 11, name: "Fúria Bestial", description: "Quando comandar o companheiro a tomar a ação Ataque, ele pode fazer dois ataques ou Multiataque se tiver." },
          { level: 15, name: "Partilha de Feitiços", description: "Quando conjurar magia mirando a si, pode fazer o efeito também ocorrer no companheiro se estiver a 9 m." },
        ],
      },
    ],
  },

  // ─── LADINO ────────────────────────────────────────────
  {
    id: "rogue",
    name: "Ladino",
    hitDie: 8,
    primaryAbilities: ["dexterity"],
    savingThrows: ["dexterity", "intelligence"],
    armorProficiencies: ["leves"],
    weaponProficiencies: ["simples", "bestas de mão", "espadas longas", "rapieiras", "espadas curtas"],
    toolProficiencies: ["Ferramentas de ladrão"],
    skillChoices: { choose: 4, from: ["acrobatics", "athletics", "deception", "insight", "intimidation", "investigation", "perception", "performance", "persuasion", "sleightOfHand", "stealth"] },
    subclassLevel: 3,
    spellcasting: noSpellcasting,
    startingEquipment: [
      "Rapieira ou espada curta",
      "Arco curto e aljava com 20 flechas, ou espada curta",
      "Pacote de ladrão, de dungeoneer ou de explorador",
      "Armadura de couro, duas adagas e ferramentas de ladrão",
    ],
    startingGoldDice: "4d4×10",
    features: [
      { level: 1, name: "Expertisco", description: "Escolha duas das suas proficiências de perícia, ou uma perícia e ferramentas de ladrão. O bônus de proficiência é dobrado para testes com elas." },
      { level: 1, name: "Ataque Furtivo", description: "Uma vez por turno, ao acertar com ataque com arma de acuidade ou à distância com vantagem (ou se um aliado estiver a 1,5 m do alvo e você não tiver desvantagem), cause dano extra de Ataque Furtivo (1d6, aumenta com nível)." },
      { level: 1, name: "Gíria de Ladrão", description: "Conhece a Gíria de Ladrão e pode esconder mensagens em conversas aparentemente normais." },
      { level: 2, name: "Ação Astuta", description: "Pode tomar Disparada, Desengajar ou Esconder-se como ação bônus no seu turno." },
      { level: 3, name: "Arquétipo Ladinesco", description: "Escolha um arquétipo." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 5, name: "Esquiva Sobrenatural", description: "Quando um atacante que você possa ver te acertar, use reação para reduzir o dano pela metade." },
      { level: 6, name: "Expertisco", description: "Escolha mais duas proficiências para expertise." },
      { level: 7, name: "Evasão", description: "Em salvaguardas de Destreza para metade do dano: nenhum em sucesso, metade em falha." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 9, name: "Característica do Arquétipo", description: "Você ganha uma característica do seu arquétipo." },
      { level: 10, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 11, name: "Talento Confiável", description: "Sempre que fizer um teste de habilidade que permita adicionar bônus de proficiência, trate d20 ≤ 9 como 10." },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 13, name: "Característica do Arquétipo", description: "Você ganha uma característica do seu arquétipo." },
      { level: 14, name: "Sentidos Cegos", description: "Se puder ouvir, conhece a localização de qualquer criatura oculta ou invisível a até 3 m." },
      { level: 15, name: "Mente Escorregadia", description: "Ganha proficiência em salvaguardas de Sabedoria." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 17, name: "Característica do Arquétipo", description: "Você ganha uma característica do seu arquétipo." },
      { level: 18, name: "Elusivo", description: "Nenhum ataque tem vantagem contra você enquanto não estiver incapacitado." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 20, name: "Golpe de Sorte", description: "Se sua jogada de ataque errar, pode virá-la em acerto. Ou se falhar em teste de habilidade, trate o d20 como 20. Uma vez por descanso curto ou longo." },
    ],
    subclasses: [
      {
        id: "thief",
        name: "Ladrão",
        description: "Você apura suas habilidades de ladrão até se tornar um especialista em furtividade, escalada e uso de itens.",
        features: [
          { level: 3, name: "Mãos Ligeiras", description: "Pode usar a ação Usar um Objeto como ação bônus. Também pode usar ferramentas de ladrão para desarmar armadilha ou abrir fechadura como ação bônus." },
          { level: 3, name: "Escalada Segunda Natureza", description: "Escalar não custa movimento extra. Quando corre, o salto em distância cobre distância adicional igual ao modificador de Destreza." },
          { level: 9, name: "Uso Mágico Supremo", description: "Você ignora todos os requisitos de classe, raça e nível para usar itens mágicos." },
          { level: 13, name: "Usar Item Mágico", description: "Pode usar qualquer pergaminho de magia. CD e ataque usam sua Inteligência. Se a magia for de nível superior ao que pode conjurar, teste de Inteligência (Arcana) CD 10 + nível da magia." },
          { level: 17, name: "Reflexos de Ladrão", description: "Pode tomar dois turnos durante o primeiro round de combate: um na iniciativa normal e outro na iniciativa −10." },
        ],
      },
      {
        id: "assassin",
        name: "Assassino",
        description: "Você se concentra no macabro artifício da morte, usando furtividade e artimanhas para eliminar alvos com eficiência mortal.",
        features: [
          { level: 3, name: "Proficiências Adicionais", description: "Proficiência com kit de disfarce e kit de envenenador." },
          { level: 3, name: "Assassinar", description: "Vantagem em ataques contra qualquer criatura que ainda não tenha agido no combate. Qualquer acerto contra criatura surpresa é crítico." },
          { level: 9, name: "Infiltração Especialista", description: "Pode criar identidades falsas. Deve gastar sete dias e 25 po para estabelecer os detalhes e a documentação." },
          { level: 13, name: "Impostor", description: "Pode imitar perfeitamente a fala, escrita e comportamento de outra pessoa. Vantagem em testes de Enganação relacionados a se passar por essa pessoa." },
          { level: 17, name: "Golpe da Morte", description: "Quando acertar criatura que está surpresa e não tenha agido, ela faz salvaguarda de Constituição (CD 8 + proficiência + Destreza) ou o dano do ataque é dobrado." },
        ],
      },
      {
        id: "arcane-trickster",
        name: "Trapaceiro Arcano",
        description: "Alguns ladinos aprimoram sua astúcia finita com um toque de magia, aprendendo truques de mago focados em ilusão e encantamento.",
        features: [
          { level: 3, name: "Conjuração", description: "Aprende truques e magias de mago (ilusão e encantamento principalmente). Inteligência é a habilidade. Conjuração de um terço. Sempre conhece a mão do mago." },
          { level: 3, name: "Mão do Mago Prestidigitadora", description: "Pode conjurar mão do mago como ação bônus. Com ela, pode estocar um objeto, usar ferramentas de ladrão à distância, ou usar Ataque Furtivo com vantagem via a mão." },
          { level: 9, name: "Deslocamento Mágico", description: "Como ação, escolha criatura voluntária a 9 m: ambos se teletransportam, trocando de lugar (se ambos forem Médios ou menores)." },
          { level: 13, name: "Versatilidade Versátil", description: "Pode roubar o conhecimento de como conjurar uma magia de outra criatura. Detalhes conforme PHB." },
          { level: 17, name: "Surpresa Espelhante", description: "Quando criatura sob efeito de sua magia de encantamento/ilusão (concentração) for alvo de ataque, use reação: o ataque é feito contra você; se errar, o atacante se torna alvo do ataque." },
        ],
      },
    ],
  },

  // ─── FEITICEIRO ────────────────────────────────────────
  {
    id: "sorcerer",
    name: "Feiticeiro",
    hitDie: 6,
    primaryAbilities: ["charisma"],
    savingThrows: ["constitution", "charisma"],
    armorProficiencies: [],
    weaponProficiencies: ["adagas", "dardos", "fundas", "cajados", "bestas leves"],
    toolProficiencies: [],
    skillChoices: { choose: 2, from: ["arcana", "deception", "insight", "intimidation", "persuasion", "religion"] },
    subclassLevel: 1,
    spellcasting: { type: "full", ability: "charisma", preparation: "known", startsAtLevel: 1 },
    startingEquipment: [
      "Besta leve e 20 virotes, ou qualquer arma simples",
      "Bolsa de componentes ou foco arcano",
      "Pacote de dungeoneer ou de explorador",
      "Duas adagas",
    ],
    startingGoldDice: "3d4×10",
    features: [
      { level: 1, name: "Conjuração", description: "Conhece truques e magias de feiticeiro. Carisma é a habilidade de conjuração." },
      { level: 1, name: "Origem Sobrenatural", description: "Escolha a origem do seu poder mágico." },
      { level: 2, name: "Fonte de Magia", description: "Possui pontos de feitiçaria iguais ao nível. Alimentam metamagia e outras opções. Recupera em descanso longo. Pode converter espaços em pontos e vice-versa." },
      { level: 3, name: "Metamagia", description: "Aprende opções de metamagia para alterar magias gastando pontos de feitiçaria. Aprende mais nos níveis 10 e 17." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 20, name: "Restauração Sobrenatural", description: "Ao terminar um descanso curto, recupera 4 pontos de feitiçaria gastos." },
    ],
    subclasses: [
      {
        id: "draconic",
        name: "Linhagem Dracônica",
        description: "Sua magia inata vem de magia de dragão misturada ao seu sangue ou ao de seus ancestrais.",
        features: [
          { level: 1, name: "Ancestral Dragão", description: "Escolha um tipo de dragão. Fala, lê e escreve Dracônico. Dobra bônus de proficiência em Carisma em interações com dragões." },
          { level: 1, name: "Resiliência Dracônica", description: "PV máximos aumentam em 1 por nível de feiticeiro. Enquanto sem armadura, CA = 13 + Destreza." },
          { level: 6, name: "Afinidade Elemental", description: "Quando conjurar magia que cause dano do tipo do seu ancestral, adicione modificador de Carisma a um dado de dano. Pode gastar 1 ponto de feitiçaria para ganhar resistência a esse dano por 1 hora." },
          { level: 14, name: "Asas de Dragão", description: "Como ação bônus, manifesta asas: ganha deslocamento de voo igual ao de caminhada. Não funcionam em armadura média/pesada." },
          { level: 18, name: "Presença Dracônica", description: "Como ação, gaste 5 pontos de feitiçaria: cada criatura à escolha a 18 m faz salvaguarda de Sabedoria ou fica enfeitiçada/amedrontada por 1 minuto." },
        ],
      },
      {
        id: "wild",
        name: "Magia Selvagem",
        description: "Sua magia inata vem das forças caóticas do caos selvagem — imprevisível e exuberante.",
        features: [
          { level: 1, name: "Surto de Magia Selvagem", description: "Imediatamente após conjurar magia de feiticeiro de 1º nível ou superior, o Mestre pode pedir que role d20. Em 1, role na tabela de Surto de Magia Selvagem." },
          { level: 1, name: "Marés do Caos", description: "Pode obter vantagem em uma jogada de ataque, teste ou salvaguarda. Após usar, o Mestre pode forçar um Surto após a próxima magia. Recupera em descanso longo." },
          { level: 6, name: "Flexibilidade do Caos", description: "Quando fizer jogada de ataque, teste ou dano de magia, pode gastar 1 ponto de feitiçaria para rerrolar até o número de dados igual ao modificador de Carisma." },
          { level: 14, name: "Caos Controlado", description: "Sempre que rolar na tabela de Surto de Magia Selvagem, pode rolar duas vezes e usar qualquer resultado." },
          { level: 18, name: "Espiral do Caos", description: "Imediatamente após rolar ou um inimigo rolar um d20, gaste 2 pontos de feitiçaria para forçar rerrolagem." },
        ],
      },
    ],
  },

  // ─── BRUXO ─────────────────────────────────────────────
  {
    id: "warlock",
    name: "Bruxo",
    hitDie: 8,
    primaryAbilities: ["charisma"],
    savingThrows: ["wisdom", "charisma"],
    armorProficiencies: ["leves"],
    weaponProficiencies: ["simples"],
    toolProficiencies: [],
    skillChoices: { choose: 2, from: ["arcana", "deception", "history", "intimidation", "investigation", "nature", "religion"] },
    subclassLevel: 1,
    spellcasting: { type: "pact", ability: "charisma", preparation: "known", startsAtLevel: 1 },
    startingEquipment: [
      "Besta leve e 20 virotes, ou qualquer arma simples",
      "Bolsa de componentes ou foco arcano",
      "Pacote de estudioso ou de dungeoneer",
      "Armadura de couro, qualquer arma simples e duas adagas",
    ],
    startingGoldDice: "4d4×10",
    features: [
      { level: 1, name: "Patrono Sobrenatural", description: "Você fez um pacto com um ser sobrenatural de outro mundo. Escolha Fiend, Archfey ou Great Old One." },
      { level: 1, name: "Magia de Pacto", description: "Conhece truques e magias de bruxo. Carisma é a habilidade. Espaços de pacto são poucos, mas de nível alto, e recuperam em descanso curto ou longo." },
      { level: 2, name: "Invocações Sobrenaturais", description: "Aprende duas invocações mágicas. Aprende mais conforme sobe de nível. Pode substituir uma ao subir de nível." },
      { level: 3, name: "Bênção de Pacto", description: "Escolha: Pacto da Corrente (familiar especial), Pacto da Lâmina (arma de pacto) ou Pacto do Tomo (Livro das Sombras com truques)." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 11, name: "Arcano Místico", description: "Escolha uma magia de 6º nível da lista de bruxo. Pode conjurá-la uma vez sem espaço; recupera em descanso longo. (7º no 13º, 8º no 15º, 9º no 17º.)" },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 20, name: "Mestre Sobrenatural", description: "Pode gastar 1 minuto implorando ao patrono para recuperar todos os espaços de pacto gastos. Uma vez por descanso longo." },
    ],
    subclasses: [
      {
        id: "fiend",
        name: "O Demônio (Patrono)",
        description: "Você fez um pacto com um demônio dos planos inferiores — um senhor demônio, arquidiabo ou outra entidade maligna de poder imenso.",
        expandedSpells: { 1: ["burning-hands", "command"], 2: ["blindness-deafness", "scorching-ray"], 3: ["fireball", "stinking-cloud"], 4: ["fire-shield", "wall-of-fire"], 5: ["flame-strike", "hallow"] },
        features: [
          { level: 1, name: "Bênção do Escuro", description: "Quando reduzir uma criatura hostil a 0 PV, ganha PV temporários iguais ao modificador de Carisma + nível de bruxo (mín. 1)." },
          { level: 6, name: "Sorte do Escuro", description: "Quando fizer teste de habilidade ou salvaguarda, adicione d10 ao resultado. Pode fazê-lo após ver a rolagem. Uma vez por descanso curto ou longo." },
          { level: 10, name: "Resiliência Fiendish", description: "Escolha um tipo de dano (exceto mágico de armas): resistência a ele após descanso curto ou longo. Pode mudar a cada descanso." },
          { level: 14, name: "Passagem pelo Inferno", description: "Quando acertar criatura, use esta característica para teleportá-la através dos planos inferiores: 10d10 de dano de fogo, depois retorna. Uma vez por descanso longo." },
        ],
      },
      {
        id: "archfey",
        name: "O Arquifada (Patrono)",
        description: "Seu patrono é um senhor ou senhora das fadas, uma criatura de lendas com segredos esquecidos pelos mortais e poder rivalizando com os deuses.",
        expandedSpells: { 1: ["faerie-fire", "sleep"], 2: ["calm-emotions", "phantasmal-force"], 3: ["blink", "plant-growth"], 4: ["dominate-beast", "greater-invisibility"], 5: ["dominate-person", "seeming"] },
        features: [
          { level: 1, name: "Presença Feérica", description: "Como ação, cada criatura à escolha a 3 m faz salvaguarda de Sabedoria ou fica enfeitiçada/amedrontada até o fim do seu próximo turno. Uma vez por descanso curto ou longo." },
          { level: 6, name: "Fuga Enevoada", description: "Quando sofrer dano, use reação para ficar invisível e se teletransportar até 18 m. Invisível até o início do próximo turno ou até atacar/conjurar. Uma vez por descanso curto ou longo." },
          { level: 10, name: "Defesas Sedutoras", description: "Imunidade a ser enfeitiçado. Quando criatura tentar enfeitiçá-lo, use reação para virar o encanto contra ela (salvaguarda de Sabedoria)." },
          { level: 14, name: "Delírio Sombrio", description: "Como ação, escolha criatura enfeitiçada por você a 1,5 m: ela fica magicamente amedrontada/incapacitada (alucinações) por 1 minuto ou até dano. Uma vez por descanso longo." },
        ],
      },
      {
        id: "great-old-one",
        name: "O Grande Antigo (Patrono)",
        description: "Seu patrono é uma entidade misteriosa cuja natureza é incompreensível para mentes mortais — talvez um Grande Antigo dos Reinos Distantes.",
        expandedSpells: { 1: ["dissonant-whispers", "tashas-hideous-laughter"], 2: ["detect-thoughts", "phantasmal-force"], 3: ["clairvoyance", "sending"], 4: ["dominate-beast", "dominate-person"], 5: ["telekinesis", "modify-memory"] },
        features: [
          { level: 1, name: "Mente Desperta", description: "Pode se comunicar telepaticamente com qualquer criatura a 9 m que entenda um idioma." },
          { level: 6, name: "Proteção Entrópica", description: "Quando criatura te acertar com ataque, use reação para impor desvantagem nessa jogada. Se o ataque errar, o próximo ataque contra o atacante antes do fim do seu próximo turno tem vantagem. Uma vez por descanso curto ou longo." },
          { level: 10, name: "Escudo Mental", description: "Resistência a dano psíquico. Quando criatura causar dano psíquico a você, ela sofre o mesmo dano." },
          { level: 14, name: "Elos Criados", description: "Pode usar ação para tocar humanoide incapacitado e criar vínculo telepático (salvaguarda de Sabedoria). Enquanto em qualquer plano, pode se comunicar e usar detect thoughts à vontade no alvo. Uma vez por descanso longo." },
        ],
      },
    ],
  },

  // ─── MAGO ──────────────────────────────────────────────
  {
    id: "wizard",
    name: "Mago",
    hitDie: 6,
    primaryAbilities: ["intelligence"],
    savingThrows: ["intelligence", "wisdom"],
    armorProficiencies: [],
    weaponProficiencies: ["adagas", "dardos", "fundas", "cajados", "bestas leves"],
    toolProficiencies: [],
    skillChoices: { choose: 2, from: ["arcana", "history", "insight", "investigation", "medicine", "religion"] },
    subclassLevel: 2,
    spellcasting: { type: "full", ability: "intelligence", preparation: "prepared", startsAtLevel: 1, ritualCasting: true },
    startingEquipment: [
      "Cajado ou adaga",
      "Bolsa de componentes ou foco arcano",
      "Pacote de estudioso ou de explorador",
      "Grimório",
    ],
    startingGoldDice: "4d4×10",
    features: [
      { level: 1, name: "Conjuração", description: "Como estudante de magia arcana, você tem um grimório com magias. Inteligência é a habilidade de conjuração. Prepare magias do grimório após descanso longo. Pode copiar magias para o grimório." },
      { level: 1, name: "Recuperação Arcana", description: "Uma vez por dia, ao terminar um descanso curto, recupere espaços de magia com nível total igual a metade do nível de mago (arredondado para cima), nenhum acima do 6º." },
      { level: 2, name: "Tradição Arcana", description: "Escolha uma das oito escolas de magia como tradição arcana." },
      { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 6, name: "Característica da Tradição", description: "Você ganha uma característica da sua tradição arcana." },
      { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 10, name: "Característica da Tradição", description: "Você ganha uma característica da sua tradição arcana." },
      { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 14, name: "Característica da Tradição", description: "Você ganha uma característica da sua tradição arcana." },
      { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 18, name: "Maestria em Magia", description: "Escolha uma magia de 1º e uma de 2º nível do grimório: pode conjurá-las em nível baixo sem gastar espaço se estiverem preparadas." },
      { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2, ou dois em 1, ou escolha um talento." },
      { level: 20, name: "Assinatura de Magia", description: "Escolha duas magias de 3º nível do grimório como assinaturas: pode conjurá-las em 3º nível sem espaço se estiverem preparadas. Pode gastar espaço para conjurá-las em nível mais alto." },
    ],
    subclasses: [
      {
        id: "abjuration",
        name: "Escola de Abjuração",
        description: "A Escola de Abjuração enfatiza magias que bloqueiam, banem ou protegem.",
        features: [
          { level: 2, name: "Sábio da Abjuração", description: "Ouro e tempo para copiar magias de abjuração são reduzidos pela metade." },
          { level: 2, name: "Proteção Arcana", description: "Quando conjurar abjuração de 1º+, cria reserva mágica (2 × nível da magia). Absorve dano. Pode reforçar com Recuperação Arcana." },
          { level: 6, name: "Projetar Proteção", description: "Como reação, quando criatura a 9 m sofrer dano, pode usar a Proteção Arcana para absorvê-lo." },
          { level: 10, name: "Abjuração Aprimorada", description: "Ao conjurar abjuração que force salvaguarda, adicione modificador de Inteligência à CD." },
          { level: 14, name: "Resistência a Magia", description: "Tem vantagem em salvaguardas contra magias. Resistência a dano de magias." },
        ],
      },
      {
        id: "conjuration",
        name: "Escola de Conjuração",
        description: "Você favorece magias que produzem objetos e criaturas do nada.",
        features: [
          { level: 2, name: "Sábio da Conjuração", description: "Ouro e tempo para copiar magias de conjuração são reduzidos pela metade." },
          { level: 2, name: "Conjuração Menor", description: "Como ação, conjure um objeto inanimado de até 1 m³ / 5 kg em espaço desocupado a 3 m. Dura 1 hora ou até ser demitido." },
          { level: 6, name: "Passo Benigno", description: "Pode usar ação bônus para se teletransportar até 9 m. Se conjurar conjuração de 1º+ no turno, o alcance do teleporte aumenta para 9 m × nível da magia." },
          { level: 10, name: "Foco Concentrado", description: "Concentração em magia de conjuração não é quebrada quando toma dano." },
          { level: 14, name: "Dureza Duradoura", description: "Criaturas que você conjura têm 30 PV temporários." },
        ],
      },
      {
        id: "divination",
        name: "Escola de Adivinhação",
        description: "O conselho dos sábios busca a verdade, a visão do passado, presente e futuro.",
        features: [
          { level: 2, name: "Sábio da Adivinhação", description: "Ouro e tempo para copiar magias de adivinhação são reduzidos pela metade." },
          { level: 2, name: "Presságio", description: "Ao terminar um descanso longo, role dois d20 e registre. Pode substituir qualquer jogada de ataque, teste ou salvaguarda (sua ou vista) por um desses resultados. Rerrola no descanso longo." },
          { level: 6, name: "Adivinhação Especialista", description: "Quando conjurar adivinhação de 2º+ usando espaço, recupere um espaço gasto de nível inferior." },
          { level: 10, name: "Terceiro Olho", description: "Como ação, ganhe um benefício até o próximo descanso: visão no escuro 18 m, ler qualquer idioma, ou visão etérea 18 m. Pode gastar espaço de 1º+ para usá-lo novamente." },
          { level: 14, name: "Maior Presságio", description: "Role três d20 para Presságio em vez de dois." },
        ],
      },
      {
        id: "enchantment",
        name: "Escola de Encantamento",
        description: "Você domina magias que encantam e iludem outras mentes.",
        features: [
          { level: 2, name: "Sábio do Encantamento", description: "Ouro e tempo para copiar magias de encantamento são reduzidos pela metade." },
          { level: 2, name: "Olhar Hipnótico", description: "Como ação, escolha criatura a 1,5 m: salvaguarda de Sabedoria ou fica enfeitiçada até o fim do seu próximo turno. Enquanto enfeitiçada, está incapacitada e tem deslocamento 0." },
          { level: 6, name: "Encanto Instintivo", description: "Quando criatura a 9 m te atacar, use reação: ela deve escolher um novo alvo ou o ataque perde. Usos = Inteligência por descanso longo." },
          { level: 10, name: "Divisão do Encanto", description: "Quando conjurar encantamento de 1º+ que mira apenas uma criatura, pode fazer mirar uma segunda criatura." },
          { level: 14, name: "Alterar Memórias", description: "Quando conjurar encantamento para encantar, pode fazer o alvo esquecer que foi encantado (salvaguarda de Inteligência)." },
        ],
      },
      {
        id: "evocation",
        name: "Escola de Evocação",
        description: "Você se concentra em magias que criam efeitos elementais poderosos: explosões de fogo, relâmpagos, frio e vento.",
        features: [
          { level: 2, name: "Sábio da Evocação", description: "Ouro e tempo para copiar magias de evocação são reduzidos pela metade." },
          { level: 2, name: "Esculpir Magias", description: "Ao conjurar evocação que afeta outras criaturas, escolha criaturas (1 + nível da magia) para sucesso automático e nenhum dano." },
          { level: 6, name: "Truque Potente", description: "Quando um truque de mago cause dano e o alvo tenha sucesso na salvaguarda para metade, o alvo sofre metade do dano do truque." },
          { level: 10, name: "Evocação Potenciada", description: "Adicione modificador de Inteligência a um dado de dano de qualquer magia de evocação de mago." },
          { level: 14, name: "Sobrecarga", description: "Ao rolar dano de evocação de 1º–5º e gastar espaço, pode gastar outro espaço do mesmo nível para maximizar o dano. Sofre dano necrótico igual ao nível do espaço × d12 e não pode conjurar no próximo turno." },
        ],
      },
      {
        id: "illusion",
        name: "Escola de Ilusão",
        description: "Você se concentra em magias que iludem os sentidos e a mente.",
        features: [
          { level: 2, name: "Sábio da Ilusão", description: "Ouro e tempo para copiar magias de ilusão são reduzidos pela metade." },
          { level: 2, name: "Ilusão Melhorada", description: "Pode conjurar ilusão menor como ação bônus. Ao conjurá-la, pode criar som e imagem juntos." },
          { level: 6, name: "Ilusões Maleáveis", description: "Pode usar ação para mudar a natureza de uma ilusão que conjurou com duração de 1 minuto+." },
          { level: 10, name: "Ilusão Sólida", description: "Quando conjurar imagem espelhada ou maior, pode tornar um objeto da ilusão real por 1 minuto (objetos não podem causar dano direto)." },
          { level: 14, name: "Realidade Ilusória", description: "Quando uma criatura discernir uma ilusão sua, você pode usar reação para causar dano psíquico (sabedoria)." },
        ],
      },
      {
        id: "necromancy",
        name: "Escola de Necromancia",
        description: "A Escola de Necromancia explora as forças que animam todos os seres vivos.",
        features: [
          { level: 2, name: "Sábio da Necromancia", description: "Ouro e tempo para copiar magias de necromancia são reduzidos pela metade." },
          { level: 2, name: "Colheita Sombria", description: "Uma vez por turno, ao matar uma ou mais criaturas com magia de 1º+, recupera PV iguais a duas vezes o nível da magia (três vezes se necromancia)." },
          { level: 6, name: "Mortos-Vivos Incontroláveis", description: "Alvos animados por animar mortos têm +PV e +dano iguais ao modificador de Inteligência. Pode comandar + mortos-vivos adicionais." },
          { level: 10, name: "Morte Inevitável", description: "Resistência a dano necrótico. Seu máximo de PV não pode ser reduzido. Ao falhar salvaguarda vs morte súbita mágica, pode ter sucesso em vez disso (uma vez por descanso longo)." },
          { level: 14, name: "Comandar Mortos-Vivos", description: "Como ação, escolha morto-vivo a 18 m: salvaguarda de Carisma ou fica sob seu controle (inteligentes têm vantagem e se libertam em sucesso posterior)." },
        ],
      },
      {
        id: "transmutation",
        name: "Escola de Transmutação",
        description: "Você é um estudante de magias que modificam energia e matéria.",
        features: [
          { level: 2, name: "Sábio da Transmutação", description: "Ouro e tempo para copiar magias de transmutação são reduzidos pela metade." },
          { level: 2, name: "Alquimia Menor", description: "Pode realizar um procedimento alquímico em um objeto não-mágico: transformar madeira em corda, metal em madeira etc., por 1 hora." },
          { level: 6, name: "Pedra do Transmutador", description: "Cria uma pedra de transmutação que concede um benefício (resistência a dano, +3 m deslocamento, visão no escuro ou +1d4 em testes de Constituição)." },
          { level: 10, name: "Metamorfo", description: "Pode conjurar polimorfar sem gastar espaço. Ao fazê-lo, só pode transformar em feras de CR 1 ou inferior. Uma vez por descanso curto ou longo." },
          { level: 14, name: "Mestre Transmutador", description: "Pode destruir a pedra de transmutação para panaceia, restaurar vida, restaurar juventude ou uma transmutação maior." },
        ],
      },
    ],
  },
];

export function getClass(id: string): ClassDefinition | undefined {
  return CLASSES.find((c) => c.id === id);
}

export function getSubclass(
  classId: string,
  subclassId: string,
): SubclassDefinition | undefined {
  return getClass(classId)?.subclasses.find((s) => s.id === subclassId);
}
