import type { ClassDefinition, ClassFeature, SubclassDefinition } from "@/config/types";

const x = (level: number, name: string, description: string, id?: string): ClassFeature => ({
  id: id ?? name.toLowerCase().replace(/\s+/g, "-"),
  level,
  name,
  description,
  source: "xgte",
});

/** Invocações místicas novas do Guia de Xanathar (selecionáveis como opcionais do bruxo). */
export const XGTE_WARLOCK_INVOCATIONS: ClassFeature[] = [
  x(2, "Aperto de Hadar", "Pré-requisito: magia braços de Hadar. Quando conjura braços de Hadar, pode fazer com que as criaturas afetadas tenham o deslocamento reduzido a 0 até o início do seu próximo turno.", "grasp-of-hadar"),
  x(2, "Arma de Pacto Aprimorada", "Pré-requisito: Pacto da Lâmina. Você pode usar qualquer arma criada pela sua arma de pacto como foco de conjuração e a arma ganha +1 nas jogadas de ataque e dano (salvo se já tiver bônus mágico).", "improved-pact-weapon"),
  x(2, "Aspecto da Lua", "Você não precisa mais dormir e não pode ser forçado a dormir por magia. Pode fazer um descanso longo enquanto permanece consciente e realiza atividades leves por 8 horas.", "aspect-of-the-moon"),
  x(5, "Dádiva das Profundezas", "Pré-requisito: 5º nível. Você pode respirar debaixo d'água e ganha deslocamento de natação igual ao terrestre. Uma vez por descanso longo, pode conjurar respirar na água em si mesmo e até 5 criaturas voluntárias sem gastar espaço.", "gift-of-the-depths"),
  x(5, "Destruição Mística", "Pré-requisito: 5º nível, Pacto da Lâmina. Uma vez por turno, quando acerta uma criatura com sua arma de pacto, pode gastar um espaço de pacto para causar dano de força extra de 1d8 por nível do espaço (+1d8 se o alvo for aberração, celestial, elemental, fada, demônio ou morto-vivo).", "eldritch-smite"),
  x(7, "Fuga do Escapista", "Pré-requisito: 7º nível, Pacto da Corrente. Como reação quando uma criatura a até 9 m que você possa ver é atingida por um ataque, dá cobertura parcial (+2 CA) até o início do próximo turno dela, ou teleporta-a até 9 m.", "escape-of-the-escapist"),
  x(5, "Lança da Letargia", "Pré-requisito: rajada mística. Quando acerta uma criatura com rajada mística, pode reduzir o deslocamento dela em 3 m até o fim do seu próximo turno.", "lance-of-lethargy"),
  x(5, "Maldição Enlouquecedora", "Pré-requisito: 5º nível, magia maldição. Como ação bônus, escolhe uma criatura amaldiçoada por você a até 9 m; criaturas à escolha a até 1,5 m dela sofrem dano psíquico igual ao seu modificador de Carisma.", "maddening-hex"),
  x(5, "Maldição Incansável", "Pré-requisito: 5º nível, magia maldição. Sua maldição não exige concentração e dura até o alvo cair a 0 PV, você conjurar a magia de novo ou um descanso curto/longo. Como ação bônus, teleporta até 9 m até o alvo amaldiçoado.", "relentless-hex"),
  x(5, "Manto de Moscas", "Pré-requisito: 5º nível. Como ação bônus, envolve-se em um manto de moscas até se mover, ser incapacitado ou dispensá-lo. Criaturas a 1,5 m sofrem dano de veneno igual ao modificador de Carisma no início do turno delas; você tem vantagem em Intimidação.", "cloak-of-flies"),
  x(7, "Olhar Fantasmagórico", "Pré-requisito: 7º nível. Como ação, força uma criatura a até 18 m a fazer salvaguarda de Sabedoria ou ficar amedrontada até o fim do seu próximo turno; deslocamento 0 enquanto amedrontada assim. PB usos por descanso longo.", "ghostly-gaze"),
  x(1, "Presente dos Sempre Vivos", "Você aprende o truque prestidigitação. Pode conjurar criar comida e água uma vez por descanso longo sem gastar espaço. Enquanto um familiar do pacto estiver a até 30 m, quando recupera PV, usa o máximo nos dados.", "gift-of-the-ever-living-ones"),
  x(15, "Sudário das Sombras", "Pré-requisito: 15º nível. Você pode se mover através de criaturas e objetos como se fossem terreno difícil; sofre 1d10 de força se terminar o turno dentro de um objeto. Também pode conjurar invisibilidade à vontade sem gastar espaço.", "shroud-of-shadow"),
  x(5, "Túmulo de Levisto", "Pré-requisito: 5º nível. Como reação quando sofre dano, ganha PV temporários iguais ao dobro do nível de bruxo + modificador de Carisma. Enquanto tiver esses PV temporários, seu deslocamento é 0 e você tem vulnerabilidade a dano de força. Uma vez por descanso curto ou longo.", "tomb-of-levistus"),
];

export const XGTE_SUBCLASSES: Record<string, SubclassDefinition[]> = {
  barbarian: [
    {
      id: "ancestral-guardian",
      name: "Caminho do Guardião Ancestral",
      source: "xgte",
      description: "Espíritos ancestrais protegem você e seus aliados em combate.",
      features: [
        x(3, "Protetores Ancestrais", "Enquanto em fúria, a primeira criatura que você acertar em cada turno tem desvantagem em ataques contra outros que não sejam você, e os outros têm resistência ao dano dela até o início do seu próximo turno."),
        x(6, "Escudo Espiritual", "Se um aliado a até 9 m sofrer dano, use reação para reduzir o dano (2d6 + nível de bárbaro, aumentando nos níveis 10 e 14)."),
        x(10, "Consulta aos Ancestrais", "Consulte os espíritos para vantagem em testes de atributo e perícias por 10 minutos (PB usos por descanso longo)."),
        x(14, "Vingança Vingativa", "Quando um aliado a até 9 m for reduzido a 0 PV, use reação para se mover até metade do deslocamento e fazer um ataque corpo a corpo; se acertar, o alvo tem desvantagem em ataques até o fim do seu próximo turno."),
      ],
    },
    {
      id: "storm-herald",
      name: "Caminho do Arauto da Tempestade",
      source: "xgte",
      description: "Sua fúria manifesta o poder de desertos, mares ou tundra.",
      features: [
        x(3, "Aura de Tempestade", "Ao entrar em fúria, escolhe Deserto, Mar ou Tundra; cria uma aura de 3 m com efeitos distintos (dano de fogo, empurrão/queda, ou PV temporários)."),
        x(6, "Alma da Tempestade", "Benefícios ambientais conforme a aura (resistência a fogo; respirar água e natação; ou caminhar em neve/gelo sem penalidade)."),
        x(10, "Escudo da Tempestade", "Reação para impor desvantagem a um ataque contra você ou aliado na aura."),
        x(14, "Tempestade Furiosa", "Aura aumenta e efeitos se intensificam; pode ativar o efeito da aura como ação bônus enquanto em fúria."),
      ],
    },
    {
      id: "zealot",
      name: "Caminho do Fanático",
      source: "xgte",
      description: "Sua fúria é um canal para o zelo divino.",
      features: [
        x(3, "Fúria Divina", "Enquanto em fúria, o primeiro ataque corpo a corpo que acertar em cada turno causa +1d6 + metade do nível de bárbaro de dano radiante ou necrótico (escolha ao ganhar a feature)."),
        x(3, "Guerreiro dos Deuses", "Se um efeito o trazer de volta à vida, o conjurador não precisa de componentes materiais que sejam consumidos."),
        x(6, "Foco Fanático", "Enquanto em fúria, rerrola uma falha em salvaguarda (uma vez por fúria)."),
        x(10, "Zelo Fanático", "Como ação bônus, concede a um aliado a até 9 m vantagem no próximo ataque (PB usos por descanso longo)."),
        x(14, "Fúria Além da Morte", "Enquanto em fúria, cair a 0 PV não o deixa inconsciente; continua lutando, fazendo salvaguardas contra morte normalmente, até a fúria acabar."),
      ],
    },
  ],
  bard: [
    {
      id: "college-of-glamour",
      name: "Colégio do Glamour",
      source: "xgte",
      description: "Você tece magia feérica de encanto e majestade.",
      features: [
        x(3, "Manto de Inspiração", "Como ação bônus, gasta um Dado de Inspiração Bárdica para dar PV temporários e permitir que aliados a até 18 m se movam sem provocar ataques de oportunidade."),
        x(3, "Presença Enfeitiçante", "Como ação, força criaturas a fazer salvaguarda de Sabedoria ou ficarem enfeitiçadas por 1 minuto (PB usos por descanso longo)."),
        x(6, "Manto de Majestade", "Conjura comando como ação bônus sem gastar espaço; enquanto mantém concentração, pode usar comando como ação bônus. Uma vez por descanso longo (ou com espaço de 3º+)."),
        x(14, "Majestade Inquebrantável", "No início do seu turno, se não tiver PV temporários, ganha PV temporários iguais ao modificador de Carisma (mín. 1). Criaturas enfeitiçadas por você têm desvantagem em salvaguardas contra suas magias de encantamento/ilusão."),
      ],
    },
    {
      id: "college-of-swords",
      name: "Colégio das Espadas",
      source: "xgte",
      description: "Você mistura lâmina e performance em floreios mortais.",
      features: [
        x(3, "Proficiência Extra", "Ganha proficiência com armadura média e a cimitarra."),
        x(3, "Estilo de Luta", "Escolhe Duelismo (+2 dano com uma arma de uma mão) ou Combate com Duas Armas (adiciona o modificador de atributo ao dano da segunda arma)."),
        x(3, "Floreio de Lâmina", "Quando acerta com ataque de arma, gasta Inspiração Bárdica para floreio Defensivo (+CA), Cortante (dano extra em outro alvo) ou Móvel (empurrão e deslocamento extra)."),
        x(6, "Ataque Extra", "Pode atacar duas vezes ao usar a ação Ataque."),
        x(14, "Floreio do Mestre", "Quando usa Floreio de Lâmina, pode rolar um d6 em vez de gastar o dado de inspiração (ainda limitado a um floreio por turno)."),
      ],
    },
    {
      id: "college-of-whispers",
      name: "Colégio dos Sussurros",
      source: "xgte",
      description: "Suas palavras plantam medo e roubam identidades.",
      features: [
        x(3, "Lâminas Psíquicas", "Quando acerta com ataque de arma, gasta Inspiração Bárdica para causar dano psíquico extra (2d6, aumentando nos níveis 5/10/15)."),
        x(3, "Palavras de Terror", "Após conversar 1 minuto com uma criatura humanaide, força salvaguarda de Sabedoria ou ela fica amedrontada de você por 1 hora ou até atacá-la (PB usos por descanso longo)."),
        x(6, "Manto das Sussurros", "Ao ver uma humanaide morrer a até 9 m, captura sua sombra por 1 hora; pode usar a ação para se disfarçar como ela, incluindo informações superficiais."),
        x(14, "Sombra do Medo", "Quando acerta Lâminas Psíquicas, pode forçar salvaguarda de Sabedoria: na falha, o alvo fica amedrontado e responde verdades a perguntas suas enquanto amedrontado."),
      ],
    },
  ],
  warlock: [
    {
      id: "the-celestial",
      name: "O Celestial",
      source: "xgte",
      description: "Seu patrono é um ser dos Planos Superiores — um unicórnio, solar ou entidade similar.",
      features: [
        x(1, "Magias Expandidas", "Aprende magias extras ligadas à luz e cura (ver lista do Celestial)."),
        x(1, "Luz Curativa", "Poço de d6 iguais ao nível de bruxo + 1; como ação bônus, gasta dados para curar uma criatura a até 18 m."),
        x(1, "Magias de Radiante", "Aprende os truques luz e chama sagrada."),
        x(6, "Alma Radiante", "Resistência a radiante; ao conjurar magia de 1º+ que cause dano, pode adicionar modificador de Carisma a um teste de dano."),
        x(10, "Resiliência Celestial", "Ao terminar descanso curto/longo, ganha PV temporários iguais ao nível de bruxo + modificador de Carisma."),
        x(14, "Vingança Sagrada", "Quando sofre dano de uma criatura a até 18 m, usa reação para forçar salvaguarda de Destreza: 2d10 + Carisma de dano radiante (metade no sucesso), e fica cega até o fim do próximo turno dela."),
      ],
      expandedSpells: {
        1: ["cure-wounds", "guiding-bolt"],
        2: ["flaming-sphere", "lesser-restoration"],
        3: ["daylight", "revivify"],
        4: ["guardian-of-faith", "wall-of-fire"],
        5: ["flame-strike", "greater-restoration"],
      },
    },
    {
      id: "the-hexblade",
      name: "A Lâmina Maldita",
      source: "xgte",
      description: "Você fez um pacto com uma entidade das Sombras que manifesta poder em armas amaldiçoadas.",
      features: [
        x(1, "Magias Expandidas", "Aprende magias extras de guerra e maldição."),
        x(1, "Guerreiro Hex", "Proficiência com armadura média, escudos e armas marciais. Pode usar Carisma em ataques/dano com uma arma de pacto (ou uma arma que esteja empunhando)."),
        x(1, "Maldição da Hexblade", "Como ação bônus, amaldiçoa um alvo a até 9 m: bônus de PB no dano, crítico em 19–20, e recupera PV se o alvo morrer (PB usos por descanso longo)."),
        x(6, "Espectro da Hexblade", "Quando mata uma humanaide, o espírito pode se tornar um espectro sob seu comando (detalhes PHB/XGtE)."),
        x(10, "Armadura da Hex", "Se não estiver de armadura pesada, pode adicionar o modificador de Carisma à CA."),
        x(14, "Mestre das Hexes", "Quando o alvo da Maldição da Hexblade cai a 0 PV, pode mover a maldição para outra criatura a até 9 m."),
      ],
      expandedSpells: {
        1: ["shield", "wrathful-smite"],
        2: ["blur", "branding-smite"],
        3: ["blink", "elemental-weapon"],
        4: ["phantasmal-killer", "staggering-smite"],
        5: ["banishing-smite", "cone-of-cold"],
      },
    },
  ],
  cleric: [
    {
      id: "forge-domain",
      name: "Domínio da Forja",
      source: "xgte",
      description: "Deuses da forja e da criação guiam suas mãos e sua fé.",
      features: [
        x(1, "Proficiências Bônus", "Proficiência com armadura pesada e ferramentas de ferreiro."),
        x(1, "Bênção da Forja", "Ao fim de um descanso longo, torna uma arma ou armadura +1 (não mágica) até o próximo descanso longo."),
        x(2, "Canalizar Divindade: Bênção do Artesão", "Conduz a criação de um item não mágico de metal, com valor e tempo reduzidos."),
        x(6, "Alma da Forja", "Resistência a fogo; enquanto usa armadura pesada, +1 CA."),
        x(8, "Golpe Divino", "Uma vez por turno, ataque de arma causa +1d8 de fogo (2d8 no 14º)."),
        x(17, "Santo da Forja", "Resistência a fogo torna-se imunidade; enquanto usa armadura pesada, resistência a dano contundente, perfurante e cortante de ataques não mágicos."),
      ],
      expandedSpells: {
        1: ["identify", "searing-smite"],
        3: ["heat-metal", "magic-weapon"],
        5: ["elemental-weapon", "protection-from-energy"],
        7: ["fabricate", "wall-of-fire"],
        9: ["animate-objects", "creation"],
      },
    },
    {
      id: "grave-domain",
      name: "Domínio da Sepultura",
      source: "xgte",
      description: "Você vigia a fronteira entre a vida e a morte.",
      features: [
        x(1, "Círculo da Mortalidade", "Quando cura uma criatura a 0 PV com magia, usa o máximo nos dados. Aprende o truque poupar os morrendo (pode conjurá-lo como ação bônus a até 9 m)."),
        x(1, "Olhos da Sepultura", "Detecta mortos-vivos a até 18 m (PB usos por descanso longo)."),
        x(2, "Canalizar Divindade: Trilha para a Sepultura", "Como ação, amaldiçoa uma criatura a até 9 m: o próximo ataque contra ela antes do fim do seu próximo turno tem vantagem e é crítico automático em acerto."),
        x(6, "Sentinela no Limiar", "Quando uma criatura a até 9 m (incluindo você) sofreria um acerto crítico, usa reação para torná-lo um acerto normal. Também não sofre os efeitos de falhar na salvaguarda de dano de um morto-vivo (ainda sofre dano parcial se houver)."),
        x(8, "Golpe Potente", "Uma vez por turno, ataque de arma causa +1d8 necrótico (2d8 no 14º)."),
        x(17, "Guardião da Alma", "No início do seu turno, escolhe criaturas a até 9 m (até o modificador de Sabedoria): elas têm resistência a todo dano até o início do seu próximo turno; a primeira vez que cada uma sofre dano, você sofre a mesma quantidade."),
      ],
      expandedSpells: {
        1: ["bane", "false-life"],
        3: ["gentle-repose", "ray-of-enfeeblement"],
        5: ["revivify", "vampiric-touch"],
        7: ["blight", "death-ward"],
        9: ["antilife-shell", "raise-dead"],
      },
    },
  ],
  druid: [
    {
      id: "circle-of-dreams",
      name: "Círculo dos Sonhos",
      source: "xgte",
      description: "Você compartilha laços com a Corte do Crepúsculo e os reinos dos sonhos.",
      features: [
        x(2, "Bálsamo da Corte de Verão", "Poço de d6 iguais ao nível de druida; como ação bônus, gasta dados para curar uma criatura a até 36 m."),
        x(6, "Laços de Refúgio", "Ao terminar descanso curto/longo, cria um santuário invisível de 9 m que avisa sobre criaturas hostis e concede PV temporários a aliados ao acordar."),
        x(10, "Caminhante Oculto", "Como ação bônus, teleporta até 18 m para um espaço em penumbra ou escuridão (número de usos = modificador de Sabedoria por descanso longo)."),
        x(14, "Andarilho dos Sonhos", "Pode viajar pelo Plano Étereo brevemente e trazer até 8 criaturas voluntárias (detalhes XGtE)."),
      ],
    },
    {
      id: "circle-of-the-shepherd",
      name: "Círculo do Pastor",
      source: "xgte",
      description: "Você invoca espíritos da natureza para proteger o rebanho.",
      features: [
        x(2, "Fala dos Espíritos", "Aprende fala com animais; pode conversar com feras e elementais."),
        x(2, "Totem Espiritual", "Como ação bônus, invoca totem (Unicórnio, Falcão ou Urso) em um espaço a até 18 m por 1 minuto, concedendo cura, vantagem ou PV temporários."),
        x(6, "Fúria Poderosa", "Quando conjura conjurar animais ou magia similar, as criaturas invocadas ganham +2 CA e +PV iguais ao seu nível de druida."),
        x(10, "Espírito Guardião", "Quando o Totem Espiritual restaura PV ou concede PV temporários, você pode adicionar seu modificador de Sabedoria."),
        x(14, "Espírito Fiel", "Quando reduzido a 0 PV, o espírito unicórnio pode imediatamente restaurar PV iguais ao dobro do nível de druida (uma vez por descanso longo)."),
      ],
    },
  ],
  sorcerer: [
    {
      id: "divine-soul",
      name: "Alma Favorecida",
      source: "xgte",
      description: "Uma faísca divina corre em suas veias — bem, mal ou equilíbrio.",
      features: [
        x(1, "Magia Divina", "Escolhe afinidade (Bem, Mal, Lei, Caos ou Neutro) e aprende uma magia bônus. Pode aprender magias da lista de clérigo além da de feiticeiro."),
        x(1, "Favor do Favorecido", "Quando falha em uma salvaguarda ou erra um ataque, pode rolar 2d4 e adicionar ao resultado (uma vez por descanso curto ou longo)."),
        x(6, "Cura Empoderada", "Quando rola dados para restaurar PV com uma magia, pode gastar 1 ponto de feitiçaria para rerrolar até dois dados."),
        x(14, "Asas Celestiais", "Como ação bônus, manifesta asas (voo igual ao deslocamento) por 1 minuto (uma vez por descanso longo, ou gastando 1 ponto de feitiçaria após o primeiro uso no dia)."),
        x(18, "Uma com o Divino", "Quando tem 0 pontos de feitiçaria e termina um descanso curto, recupera 4 pontos."),
      ],
    },
    {
      id: "shadow-magic",
      name: "Adepto das Sombras",
      source: "xgte",
      description: "Você carrega uma conexão sombria com o Plano das Sombras.",
      features: [
        x(1, "Olhos da Escuridão", "Visão no escuro 36 m; aprende escuridão, que pode conjurar gastando 2 pontos de feitiçaria sem espaço; pode ver através dessa escuridão."),
        x(1, "Força das Sombras", "Quando reduzido a 0 PV, pode fazer salvaguarda de Carisma (CD 5 + dano) para cair a 1 PV (uma vez por descanso longo)."),
        x(3, "Cão das Sombras", "Pode conjurar um cão da morte das sombras (estatísticas especiais) gastando pontos de feitiçaria."),
        x(6, "Andarilho das Sombras", "Como ação bônus, teleporta até 36 m de uma área de penumbra/escuridão para outra (PB usos por descanso longo)."),
        x(14, "Forma Sombria", "Como ação bônus, torna-se uma sombra (resistências, mover-se por espaços estreitos) por 1 minuto (1 ponto de feitiçaria)."),
      ],
    },
    {
      id: "storm-sorcery",
      name: "Feiticeiro da Tempestade",
      source: "xgte",
      description: "Seu poder nasce do vento, do trovão e da tempestade.",
      features: [
        x(1, "Fala do Vento", "Aprende Primordial; deslocamento de voo limitado imediatamente após conjurar magia de 1º+."),
        x(1, "Magia Tempestuosa", "Imediatamente após conjurar magia de 1º+, voa 3 m sem provocar ataques de oportunidade."),
        x(6, "Coração da Tempestade", "Resistência a relâmpago e trovão; após conjurar magia de 1º+ que cause esses danos, cria uma tempestade de 3 m que causa dano a inimigos."),
        x(6, "Guia da Tempestade", "Quando é atingido por ataque corpo a corpo, reação para empurrar o atacante 6 m."),
        x(14, "Fúria da Tempestade", "Quando é atingido por ataque corpo a corpo, reação para causar dano de relâmpago e empurrar o atacante."),
        x(18, "Alma do Vento", "Deslocamento de voo igual ao terrestre; magias de tempestade podem empurrar criaturas grandes."),
      ],
    },
  ],
  fighter: [
    {
      id: "arcane-archer",
      name: "Arqueiro Arcano",
      source: "xgte",
      description: "Você imbuí flechas com magia élfica precisa.",
      features: [
        x(3, "Disparo Arcano", "Aprende duas opções de Disparo Arcano (Explosão, Sedução, Agarrar, Banimento, Enfraquecimento, Perfurante, Perseguidora, Sombria). Usa duas vezes por descanso curto/longo; aprende mais opções nos níveis 7, 10, 15 e 18."),
        x(3, "Tiro Arcano", "Proficiência em Arcanismo ou Natureza; cria flechas mágicas +1 (não acumulam com outras magias) após descanso curto/longo."),
        x(7, "Flecha Curativa", "Uma vez por descanso curto/longo, cura um aliado a até 9 m com uma flecha (2d6 + modificador de Inteligência)."),
        x(15, "Disparo Sempre Pronto", "Quando rola iniciativa e não tem usos de Disparo Arcano, recupera um uso."),
      ],
    },
    {
      id: "cavalier",
      name: "Cavaleiro",
      source: "xgte",
      description: "Você é o protetor montado e o guardião da linha de frente.",
      features: [
        x(3, "Nascimento na Sela", "Vantagem para permanecer montado; montar/desmontar custa 1,5 m; aterrissagem forçada reduz dano."),
        x(3, "Marca Inabalável", "Como ação bônus, marca um inimigo: vantagem nos ataques contra ele e reação para atacar se ele atacar outro."),
        x(7, "Guardião Feroz", "Imõe desvantagem a ataques contra aliados a 1,5 m; reação para atacar quem se move para fora do alcance."),
        x(10, "Segure a Linha", "Ao acertar com ataque de oportunidade, o deslocamento do alvo se torna 0."),
        x(15, "Defesa Feroz", "Quando um aliado a 1,5 m é atacado, reação para se tornar o alvo do ataque."),
        x(18, "Espírito Vigilante", "Marca Inabalável e reações de guardião se aprimoram; mais usos e alcance."),
      ],
    },
    {
      id: "samurai",
      name: "Samurai",
      source: "xgte",
      description: "Você canaliza uma disciplina implacável e um espírito inquebrantável.",
      features: [
        x(3, "Espírito Combativo", "Como ação bônus, ganha vantagem em todos os ataques do turno (PB usos por descanso longo)."),
        x(3, "Cortesia Elegante", "Proficiência em História, Insight, Performance ou Persuasão; dobra o PB nessa perícia."),
        x(7, "Força Elegante", "Ao usar Espírito Combativo, ganha PV temporários iguais ao dobro do nível de guerreiro."),
        x(10, "Espírito Incansável", "Quando rola iniciativa e não tem usos de Espírito Combativo, recupera um uso."),
        x(15, "Combate Acelerado", "Pode fazer um ataque de arma como ação bônus no turno em que usa a ação Ataque."),
        x(18, "Força de Vontade", "Vantagem em salvaguardas de Sabedoria; quando inicia o turno amedrontado ou enfeitiçado, pode terminar o efeito."),
      ],
    },
  ],
  rogue: [
    {
      id: "inquisitive",
      name: "Inquiridor",
      source: "xgte",
      description: "Nada escapa aos seus olhos e à sua dedução.",
      features: [
        x(3, "Ouvido para a Mentira", "Vantagem em Insight para detectar mentiras; pode usar Insight no lugar de Percepção para detectar escondidos."),
        x(3, "Olho para o Detalhe", "Como ação bônus, faz Percepção para detectar escondidos ou Investigação para encontrar/desarmar armadilhas e portas secretas."),
        x(3, "Olho Perspicaz", "Pode usar uma ação bônus para estudar uma criatura e obter vantagem no próximo ataque (e Ataque Furtivo sem vantagem se estiver a até 1,5 m)."),
        x(9, "Insightoso", "Nunca tem desvantagem em Insight; lê emoções e intenções com mais precisão."),
        x(13, "Olho Constantemente Aberto", "Vantagem em Iniciativa; não pode ser surpreendido; detecta ilusões mais facilmente."),
        x(17, "Olho da Mente", "Uma vez por turno, quando usa Ataque Furtivo, força salvaguarda de Sabedoria: na falha, o alvo fica atordoado até o início do seu próximo turno."),
      ],
    },
    {
      id: "mastermind",
      name: "Mentor",
      source: "xgte",
      description: "Você é o cérebro por trás de cada plano.",
      features: [
        x(3, "Maestria em Táticas", "Como ação bônus, usa a ação Ajuda para ajudar um aliado a até 9 m a atacar."),
        x(3, "Palavra Mestra", "Aprende dois idiomas; pode imitar fala após 1 minuto de observação; vantagem em testes para se passar por outro."),
        x(9, "Compreensão Insightosa", "Se passar 1 minuto observando uma criatura fora de combate, aprende se ela é igual/superior/inferior em dois atributos, CA e níveis de classe."),
        x(13, "Desorientação", "Quando uma criatura erra um ataque contra você, reação para forçar outro ataque dela contra uma criatura a 1,5 m."),
        x(17, "Alma de Traição", "Pode se teletransportar com um alvo agarrado e forçar ataques entre inimigos próximos."),
      ],
    },
    {
      id: "scout",
      name: "Batedor",
      source: "xgte",
      description: "Você é a vanguarda — rápido, alerta e mortal à distância.",
      features: [
        x(3, "Escaramuçador", "No primeiro turno de combate, seu deslocamento aumenta 3 m; reação para se mover até metade do deslocamento quando um inimigo termina o turno a 1,5 m."),
        x(3, "Sobrevivênciaista", "Proficiência em Natureza e Sobrevivência; dobra o PB nessas perícias."),
        x(9, "Mobilidade Superior", "Deslocamento +3 m; terreno difícil não reduz seu deslocamento no turno."),
        x(13, "Emboscada", "No primeiro turno, vantagem em ataques contra criaturas que ainda não agiram."),
        x(17, "Fuga Instantânea", "No final do turno de outra criatura, usa reação para se mover até o dobro do deslocamento sem provocar ataques de oportunidade."),
      ],
    },
    {
      id: "swashbuckler",
      name: "Espadachim",
      source: "xgte",
      description: "Você luta com estilo, ousadia e precisão mortal.",
      features: [
        x(3, "Lábia Fancy", "Adiciona o modificador de Carisma à iniciativa; Ataque Furtivo sem vantagem se estiver a 1,5 m do alvo e nenhum outro inimigo estiver a 1,5 m de você."),
        x(3, "Acrobata Audaz", "Não provoca ataques de oportunidade de criaturas que você atacou neste turno."),
        x(9, "Panache", "Como ação, desafia uma criatura: se falhar em Sabedoria, fica desfavorecida contra outros e você tem vantagem; ou enfeitiça se não for hostil."),
        x(13, "Elegante Manobra", "Como ação bônus, faz Acrobacia ou Atletismo."),
        x(17, "Mestre Duelista", "Se errar um ataque, pode rerrolar com vantagem (uma vez por turno)."),
      ],
    },
  ],
  wizard: [
    {
      id: "war-magic",
      name: "Mago de Guerra",
      source: "xgte",
      description: "Você funde magia ofensiva e defesa tática no campo de batalha.",
      features: [
        x(2, "Surto Arcano", "Quando causa dano com uma magia de mago de 1º+, usa ação bônus para fazer um ataque com arma."),
        x(2, "Defesa Tática", "Quando conjura uma magia de mago de 1º+, ganha +2 CA até o início do próximo turno se não estiver incapacitado."),
        x(6, "Poder Arcano", "Adiciona o modificador de Inteligência às jogadas de iniciativa; pode gastar um espaço de magia para rerrolar um ataque de magia (bônus = nível do espaço)."),
        x(10, "Desvio Durável", "Quando sofre dano, reação para reduzir o dano em 1d10 + Inteligência + nível de mago (gastando um espaço de magia para aprimorar)."),
        x(14, "Defletor Aprimorado", "Quando usa Desvio Durável contra um ataque, pode fazer o atacante sofrer força igual à redução se estiver a até 18 m."),
      ],
    },
  ],
  monk: [
    {
      id: "drunken-master",
      name: "Estilo do Mestre Bêbado",
      source: "xgte",
      description: "Seus movimentos erráticos confundem os inimigos.",
      features: [
        x(3, "Técnica Bêbada", "Proficiência em Performance; quando usa Rajada de Golpes, pode impor desvantagem ao próximo ataque contra você e se afastar 1,5–3 m sem provocar oportunidade."),
        x(6, "Dança da Bebida", "Deslocamento +3 m; oportunidades contra você têm desvantagem; se um ataque errar, reação para se mover 1,5–3 m."),
        x(11, "Sorte do Bêbado", "Quando faz um teste de atributo, ataque ou salvaguarda e tem desvantagem, pode gastar 2 ki para cancelar a desvantagem."),
        x(17, "Fúria Intoxicante", "Quando usa Rajada de Golpes, pode fazer até três ataques extras gastando ki; se errar, o próximo ataque tem vantagem."),
      ],
    },
    {
      id: "kensei",
      name: "Estilo do Kensei",
      source: "xgte",
      description: "Você trata armas como extensão do ki.",
      features: [
        x(3, "Trilha do Kensei", "Escolhe armas kensei (corpo a corpo e à distância); elas contam como artes marciais. Agilidade Kensei: ação bônus para +2 CA após ataque com arma kensei. Precisão Kensei: +dado de artes marciais no ataque à distância kensei."),
        x(3, "Caminho do Pincel", "Proficiência com utensílios de calígrafo ou de pintor."),
        x(6, "Uma com a Lâmina", "Ataques com armas kensei contam como mágicos; pode gastar 1 ki para +1d4 no ataque com arma kensei (Deleitar o Ki)."),
        x(11, "Afiado como Navalha", "Como ação bônus, torna armas kensei +3 de dano até o fim do turno (1 ki)."),
        x(17, "Mestre Inabalável", "Se errar um ataque no turno, ganha até o fim do turno +ao próximo ataque igual ao modificador de Sabedoria (mín. 1) e pode gastar ki para estender."),
      ],
    },
    {
      id: "sun-soul",
      name: "Estilo da Alma Solar",
      source: "xgte",
      description: "Você irradia a luz do sol em rajadas flamejantes.",
      features: [
        x(3, "Rajada Radiante", "Ataque desarmado à distância (9 m) que causa dano radiante; pode substituir ataques da Rajada de Golpes por rajadas."),
        x(6, "Arco Solar Ardente", "Como ação, lança um arco de luz (custo de ki) que causa dano radiante e fogo em linha."),
        x(11, "Explosão Solar Ardente", "Como ação, explode luz em esfera (custo de ki); salvaguarda de Constituição ou cegueira."),
        x(17, "Escudo Solar", "Quando é atingido por um ataque corpo a corpo ou reduzido a metade dos PV, causa dano radiante ao atacante e pode se tornar luz intensa."),
      ],
    },
  ],
  paladin: [
    {
      id: "oath-of-conquest",
      name: "Juramento da Conquista",
      source: "xgte",
      description: "Você impõe ordem pelo medo e pela força.",
      features: [
        x(3, "Canalizar Divindade: Lança Conquistadora", "Como ação bônus, marca um inimigo: o próximo ataque tem vantagem e causa dano psíquico extra."),
        x(3, "Canalizar Divindade: Presença Guiada pelo Medo", "Como ação, força criaturas a até 9 m a fazer salvaguarda de Sabedoria ou ficarem amedrontadas por 1 minuto."),
        x(7, "Aura de Conquista", "Criaturas amedrontadas a até 3 m (9 m no 18º) têm deslocamento 0 e sofrem dano psíquico no início do turno."),
        x(15, "Fúria Impiedosa", "Vantagem contra ser amedrontado; se reduzido a 0 PV, pode fazer salvaguarda para cair a 1 PV (uma vez por descanso longo)."),
        x(20, "Avatar Invencível", "Por 1 minuto, resistência a todo dano, imune a amedrontado, e quando acerta com ataque de arma força salvaguarda ou fica amedrontado e caído."),
      ],
      expandedSpells: {
        3: ["armor-of-agathys", "command"],
        5: ["hold-person", "spiritual-weapon"],
        9: ["bestow-curse", "fear"],
        13: ["dominate-beast", "stoneskin"],
        17: ["cloudkill", "dominate-person"],
      },
    },
    {
      id: "oath-of-redemption",
      name: "Juramento da Redenção",
      source: "xgte",
      description: "Você busca a paz — e combate apenas como último recurso.",
      features: [
        x(3, "Canalizar Divindade: Escudo do Emissário", "Como reação quando um aliado a até 9 m é atacado, impõe desvantagem ao ataque; se errar, o atacante sofre dano radiante."),
        x(3, "Canalizar Divindade: Repreensão", "Como ação, força uma criatura a ouvir suas palavras; salvaguarda de Sabedoria ou fica amedrontada / enfeitiçada (conforme intenção)."),
        x(7, "Aura do Guardião", "Quando um aliado a até 3 m (9 m no 18º) sofre dano, você pode usar reação para sofrer o dano no lugar (resistência a esse dano)."),
        x(15, "Espírito Protetor", "Quando um aliado a até 9 m é reduzido a 0 PV, você pode usar reação para restaurar 1d6 + nível de paladino de PV."),
        x(20, "Emissário da Redenção", "Por 1 minuto, resistência a todo dano de criaturas que você não atacou; atacantes sofrem dano radiante igual ao metade do dano que causaram a você."),
      ],
      expandedSpells: {
        3: ["sanctuary", "sleep"],
        5: ["calm-emotions", "hold-person"],
        9: ["counterspell", "hypnotic-pattern"],
        13: ["otilukes-resilient-sphere", "stoneskin"],
        17: ["hold-monster", "wall-of-force"],
      },
    },
  ],
  ranger: [
    {
      id: "gloom-stalker",
      name: "Perseguidor Obscuro",
      source: "xgte",
      description: "Você caça nas trevas do Subterrâneo e das sombras.",
      features: [
        x(3, "Emboscador", "Bônus de Sabedoria na iniciativa; no primeiro turno, deslocamento +3 m e um ataque extra que causa dano psíquico adicional."),
        x(3, "Vista Umbral", "Visão no escuro 18 m (ou +18 m); invisível à visão no escuro enquanto estiver na escuridão."),
        x(3, "Magias de Perseguidor", "Aprende magias extras do arquétipo."),
        x(7, "Mente de Ferro", "Vantagem em salvaguardas de Sabedoria; resistência a dano psíquico."),
        x(11, "Ataque Espectral", "Quando ataca uma criatura, pode atacar uma segunda criatura no alcance com o mesmo ataque (uma vez por turno)."),
        x(15, "Véu Sombrio", "Quando é atingido por um ataque, reação para se tornar invisível e se teleportar até 6 m; o ataque erra se você ainda estiver no alcance."),
      ],
      expandedSpells: {
        3: ["disguise-self"],
        5: ["rope-trick"],
        9: ["fear"],
        13: ["greater-invisibility"],
        17: ["seeming"],
      },
    },
    {
      id: "horizon-walker",
      name: "Andarilho do Horizonte",
      source: "xgte",
      description: "Você patrulha as fronteiras entre os planos.",
      features: [
        x(3, "Detectar Portal", "Detecta portais planares a até 1,6 km (ação, PB usos por descanso longo)."),
        x(3, "Golpe Planar", "Como ação bônus, marca um alvo: o próximo acerto causa dano de força extra."),
        x(3, "Magias de Andarilho", "Aprende magias extras do arquétipo."),
        x(7, "Passo Etéreo", "Como ação bônus, entra no Étereo até o fim do turno (PB usos por descanso longo)."),
        x(11, "Golpe Planar Distante", "Golpe Planar causa mais dano e pode afetar duas criaturas."),
        x(15, "Andarilho Espectral", "Quando é atacado, reação para ganhar resistência a todo dano do ataque e se teleportar até 9 m."),
      ],
      expandedSpells: {
        3: ["protection-from-evil-and-good"],
        5: ["misty-step"],
        9: ["haste"],
        13: ["banishment"],
        17: ["teleportation-circle"],
      },
    },
    {
      id: "monster-slayer",
      name: "Exterminador de Monstros",
      source: "xgte",
      description: "Você é especialista em abater ameaças sobrenaturais.",
      features: [
        x(3, "Presa do Caçador", "Como ação bônus, concentra-se em um alvo: o primeiro acerto em cada turno causa dano extra igual ao modificador de Sabedoria."),
        x(3, "Sentido Sobrenatural", "Aprende a detectar magia; como ação, analisa uma criatura para aprender imunidades, resistências e vulnerabilidades."),
        x(3, "Magias de Exterminador", "Aprende magias extras do arquétipo."),
        x(7, "Escudo Sobrenatural", "Quando o alvo da Presa do Caçador o força a uma salvaguarda ou você faz um teste de resistência contra magia dele, adicione o modificador de Sabedoria."),
        x(11, "Golpe do Exterminador", "Uma vez por turno, quando acerta o alvo marcado, causa 1d6 de dano extra e força salvaguarda de Força ou fica contido até o início do seu próximo turno."),
        x(15, "Defesa do Caçador", "Quando o alvo marcado o força a uma salvaguarda e você tem sucesso, reação para causar dano de força iguais ao espaço de magia ou 1d10 + Sabedoria."),
      ],
      expandedSpells: {
        3: ["protection-from-evil-and-good"],
        5: ["zone-of-truth"],
        9: ["magic-circle"],
        13: ["banishment"],
        17: ["hold-monster"],
      },
    },
  ],
};

export function enrichClassesWithXgte(classes: ClassDefinition[]): ClassDefinition[] {
  return classes.map((cls) => {
    const extras = XGTE_SUBCLASSES[cls.id] ?? [];
    if (!extras.length) return cls;
    return {
      ...cls,
      subclasses: [...cls.subclasses, ...extras],
    };
  });
}
