import type { ArmorDefinition, WeaponDefinition } from "@/config/types";

export const ARMORS: ArmorDefinition[] = [
  {
    id: "padded",
    name: "Acolchoada",
    category: "light",
    baseAc: 11,
    dexCap: null,
    stealthDisadvantage: true,
    costGp: 5,
    weight: 8,
  },
  {
    id: "leather",
    name: "Couro",
    category: "light",
    baseAc: 11,
    dexCap: null,
    stealthDisadvantage: false,
    costGp: 10,
    weight: 10,
  },
  {
    id: "studded-leather",
    name: "Couro Batido",
    category: "light",
    baseAc: 12,
    dexCap: null,
    stealthDisadvantage: false,
    costGp: 45,
    weight: 13,
  },
  {
    id: "hide",
    name: "Pele",
    category: "medium",
    baseAc: 12,
    dexCap: 2,
    stealthDisadvantage: false,
    costGp: 10,
    weight: 12,
  },
  {
    id: "chain-shirt",
    name: "Camisão de Malha",
    category: "medium",
    baseAc: 13,
    dexCap: 2,
    stealthDisadvantage: false,
    costGp: 50,
    weight: 20,
  },
  {
    id: "scale-mail",
    name: "Cota de Escamas",
    category: "medium",
    baseAc: 14,
    dexCap: 2,
    stealthDisadvantage: true,
    costGp: 50,
    weight: 45,
  },
  {
    id: "breastplate",
    name: "Peitoral",
    category: "medium",
    baseAc: 14,
    dexCap: 2,
    stealthDisadvantage: false,
    costGp: 400,
    weight: 20,
  },
  {
    id: "half-plate",
    name: "Meia-Armadura",
    category: "medium",
    baseAc: 15,
    dexCap: 2,
    stealthDisadvantage: true,
    costGp: 750,
    weight: 40,
  },
  {
    id: "ring-mail",
    name: "Cota de Anéis",
    category: "heavy",
    baseAc: 14,
    dexCap: 0,
    stealthDisadvantage: true,
    costGp: 30,
    weight: 40,
  },
  {
    id: "chain-mail",
    name: "Cota de Malha",
    category: "heavy",
    baseAc: 16,
    dexCap: 0,
    stealthDisadvantage: true,
    strengthRequirement: 13,
    costGp: 75,
    weight: 55,
  },
  {
    id: "splint",
    name: "Armadura de Talas",
    category: "heavy",
    baseAc: 17,
    dexCap: 0,
    stealthDisadvantage: true,
    strengthRequirement: 15,
    costGp: 200,
    weight: 60,
  },
  {
    id: "plate",
    name: "Armadura de Placas",
    category: "heavy",
    baseAc: 18,
    dexCap: 0,
    stealthDisadvantage: true,
    strengthRequirement: 15,
    costGp: 1500,
    weight: 65,
  },
  {
    id: "shield",
    name: "Escudo",
    category: "shield",
    baseAc: 2,
    dexCap: null,
    stealthDisadvantage: false,
    costGp: 10,
    weight: 6,
  },
];

export const WEAPONS: WeaponDefinition[] = [
  // Simple Melee
  {
    id: "club",
    name: "Clava",
    category: "simple",
    range: "melee",
    damage: "1d4",
    damageType: "concussão",
    properties: ["leve"],
    costGp: 0.1,
    weight: 2,
  },
  {
    id: "dagger",
    name: "Adaga",
    category: "simple",
    range: "melee",
    damage: "1d4",
    damageType: "perfurante",
    properties: ["acuidade", "leve", "arremesso (6/18 m)"],
    costGp: 2,
    weight: 1,
    finesse: true,
  },
  {
    id: "greatclub",
    name: "Clava Grande",
    category: "simple",
    range: "melee",
    damage: "1d8",
    damageType: "concussão",
    properties: ["duas mãos"],
    costGp: 0.2,
    weight: 10,
  },
  {
    id: "handaxe",
    name: "Machadinha",
    category: "simple",
    range: "melee",
    damage: "1d6",
    damageType: "cortante",
    properties: ["leve", "arremesso (6/18 m)"],
    costGp: 5,
    weight: 2,
  },
  {
    id: "javelin",
    name: "Azagaia",
    category: "simple",
    range: "melee",
    damage: "1d6",
    damageType: "perfurante",
    properties: ["arremesso (9/36 m)"],
    costGp: 0.5,
    weight: 2,
  },
  {
    id: "light-hammer",
    name: "Martelo Leve",
    category: "simple",
    range: "melee",
    damage: "1d4",
    damageType: "concussão",
    properties: ["leve", "arremesso (6/18 m)"],
    costGp: 2,
    weight: 2,
  },
  {
    id: "mace",
    name: "Maça",
    category: "simple",
    range: "melee",
    damage: "1d6",
    damageType: "concussão",
    properties: [],
    costGp: 5,
    weight: 4,
  },
  {
    id: "quarterstaff",
    name: "Cajado",
    category: "simple",
    range: "melee",
    damage: "1d6",
    damageType: "concussão",
    properties: ["versátil (1d8)"],
    costGp: 0.2,
    weight: 4,
    versatile: "1d8",
  },
  {
    id: "sickle",
    name: "Foice",
    category: "simple",
    range: "melee",
    damage: "1d4",
    damageType: "cortante",
    properties: ["leve"],
    costGp: 1,
    weight: 2,
  },
  {
    id: "spear",
    name: "Lança",
    category: "simple",
    range: "melee",
    damage: "1d6",
    damageType: "perfurante",
    properties: ["arremesso (6/18 m)", "versátil (1d8)"],
    costGp: 1,
    weight: 3,
    versatile: "1d8",
  },
  // Simple Ranged
  {
    id: "light-crossbow",
    name: "Besta Leve",
    category: "simple",
    range: "ranged",
    damage: "1d8",
    damageType: "perfurante",
    properties: ["munição (24/96 m)", "recarga", "duas mãos"],
    costGp: 25,
    weight: 5,
  },
  {
    id: "dart",
    name: "Dardo",
    category: "simple",
    range: "ranged",
    damage: "1d4",
    damageType: "perfurante",
    properties: ["acuidade", "arremesso (6/18 m)"],
    costGp: 0.05,
    weight: 0.25,
    finesse: true,
  },
  {
    id: "shortbow",
    name: "Arco Curto",
    category: "simple",
    range: "ranged",
    damage: "1d6",
    damageType: "perfurante",
    properties: ["munição (24/96 m)", "duas mãos"],
    costGp: 25,
    weight: 2,
  },
  {
    id: "sling",
    name: "Funda",
    category: "simple",
    range: "ranged",
    damage: "1d4",
    damageType: "concussão",
    properties: ["munição (9/36 m)"],
    costGp: 0.1,
    weight: 0,
  },
  // Martial Melee
  {
    id: "battleaxe",
    name: "Machado de Batalha",
    category: "martial",
    range: "melee",
    damage: "1d8",
    damageType: "cortante",
    properties: ["versátil (1d10)"],
    costGp: 10,
    weight: 4,
    versatile: "1d10",
  },
  {
    id: "flail",
    name: "Mangual",
    category: "martial",
    range: "melee",
    damage: "1d8",
    damageType: "concussão",
    properties: [],
    costGp: 10,
    weight: 2,
  },
  {
    id: "glaive",
    name: "Glaive",
    category: "martial",
    range: "melee",
    damage: "1d10",
    damageType: "cortante",
    properties: ["pesada", "alcance", "duas mãos"],
    costGp: 20,
    weight: 6,
  },
  {
    id: "greataxe",
    name: "Machado Grande",
    category: "martial",
    range: "melee",
    damage: "1d12",
    damageType: "cortante",
    properties: ["pesada", "duas mãos"],
    costGp: 30,
    weight: 7,
  },
  {
    id: "greatsword",
    name: "Espada Grande",
    category: "martial",
    range: "melee",
    damage: "2d6",
    damageType: "cortante",
    properties: ["pesada", "duas mãos"],
    costGp: 50,
    weight: 6,
  },
  {
    id: "halberd",
    name: "Alabarda",
    category: "martial",
    range: "melee",
    damage: "1d10",
    damageType: "cortante",
    properties: ["pesada", "alcance", "duas mãos"],
    costGp: 20,
    weight: 6,
  },
  {
    id: "lance",
    name: "Lança de Cavalaria",
    category: "martial",
    range: "melee",
    damage: "1d12",
    damageType: "perfurante",
    properties: ["alcance", "especial"],
    costGp: 10,
    weight: 6,
  },
  {
    id: "longsword",
    name: "Espada Longa",
    category: "martial",
    range: "melee",
    damage: "1d8",
    damageType: "cortante",
    properties: ["versátil (1d10)"],
    costGp: 15,
    weight: 3,
    versatile: "1d10",
  },
  {
    id: "maul",
    name: "Malho",
    category: "martial",
    range: "melee",
    damage: "2d6",
    damageType: "concussão",
    properties: ["pesada", "duas mãos"],
    costGp: 10,
    weight: 10,
  },
  {
    id: "morningstar",
    name: "Maça-Estrela",
    category: "martial",
    range: "melee",
    damage: "1d8",
    damageType: "perfurante",
    properties: [],
    costGp: 15,
    weight: 4,
  },
  {
    id: "pike",
    name: "Pique",
    category: "martial",
    range: "melee",
    damage: "1d10",
    damageType: "perfurante",
    properties: ["pesada", "alcance", "duas mãos"],
    costGp: 5,
    weight: 18,
  },
  {
    id: "rapier",
    name: "Rapieira",
    category: "martial",
    range: "melee",
    damage: "1d8",
    damageType: "perfurante",
    properties: ["acuidade"],
    costGp: 25,
    weight: 2,
    finesse: true,
  },
  {
    id: "scimitar",
    name: "Cimitarra",
    category: "martial",
    range: "melee",
    damage: "1d6",
    damageType: "cortante",
    properties: ["acuidade", "leve"],
    costGp: 25,
    weight: 3,
    finesse: true,
  },
  {
    id: "shortsword",
    name: "Espada Curta",
    category: "martial",
    range: "melee",
    damage: "1d6",
    damageType: "perfurante",
    properties: ["acuidade", "leve"],
    costGp: 10,
    weight: 2,
    finesse: true,
  },
  {
    id: "trident",
    name: "Tridente",
    category: "martial",
    range: "melee",
    damage: "1d6",
    damageType: "perfurante",
    properties: ["arremesso (6/18 m)", "versátil (1d8)"],
    costGp: 5,
    weight: 4,
    versatile: "1d8",
  },
  {
    id: "war-pick",
    name: "Picareta de Guerra",
    category: "martial",
    range: "melee",
    damage: "1d8",
    damageType: "perfurante",
    properties: [],
    costGp: 5,
    weight: 2,
  },
  {
    id: "warhammer",
    name: "Martelo de Guerra",
    category: "martial",
    range: "melee",
    damage: "1d8",
    damageType: "concussão",
    properties: ["versátil (1d10)"],
    costGp: 15,
    weight: 2,
    versatile: "1d10",
  },
  {
    id: "whip",
    name: "Chicote",
    category: "martial",
    range: "melee",
    damage: "1d4",
    damageType: "cortante",
    properties: ["acuidade", "alcance"],
    costGp: 2,
    weight: 3,
    finesse: true,
  },
  // Martial Ranged
  {
    id: "blowgun",
    name: "Zarabatana",
    category: "martial",
    range: "ranged",
    damage: "1",
    damageType: "perfurante",
    properties: ["munição (7,5/30 m)", "carregamento"],
    costGp: 10,
    weight: 1,
  },
  {
    id: "hand-crossbow",
    name: "Besta de Mão",
    category: "martial",
    range: "ranged",
    damage: "1d6",
    damageType: "perfurante",
    properties: ["munição (9/36 m)", "leve", "recarga"],
    costGp: 75,
    weight: 3,
  },
  {
    id: "heavy-crossbow",
    name: "Besta Pesada",
    category: "martial",
    range: "ranged",
    damage: "1d10",
    damageType: "perfurante",
    properties: ["munição (30/120 m)", "pesada", "recarga", "duas mãos"],
    costGp: 50,
    weight: 18,
  },
  {
    id: "longbow",
    name: "Arco Longo",
    category: "martial",
    range: "ranged",
    damage: "1d8",
    damageType: "perfurante",
    properties: ["munição (45/180 m)", "pesada", "duas mãos"],
    costGp: 50,
    weight: 2,
  },
  {
    id: "net",
    name: "Rede",
    category: "martial",
    range: "ranged",
    damage: "—",
    damageType: "—",
    properties: ["especial", "arremesso (1,5/4,5 m)"],
    costGp: 1,
    weight: 3,
  },
];

export function getArmor(id: string): ArmorDefinition | undefined {
  return ARMORS.find((a) => a.id === id);
}

export function getWeapon(id: string): WeaponDefinition | undefined {
  return WEAPONS.find((w) => w.id === id);
}
