import type { SpellDefinition } from "@/config/types";

/** Magias do Artífice (Tasha) ausentes do catálogo SRD base. */
export const ARTIFICER_EXTRA_SPELLS: SpellDefinition[] = [
  {
    id: "mending",
    name: "Reparar",
    level: 0,
    school: "transmutation",
    ritual: false,
    castingTime: "1 minuto",
    range: "Toque",
    components: { v: true, s: true, m: "dois ímãs" },
    duration: "Instantânea",
    concentration: false,
    description:
      "Você repara uma única quebra ou rasgo em um objeto que tocar, como um elo quebrado de uma corrente, dois metades de uma chave partida ou um manto rasgado.",
  },
  {
    id: "booming-blade",
    name: "Lâmina Estrondosa",
    level: 0,
    school: "evocation",
    ritual: false,
    castingTime: "1 ação",
    range: "Pessoal (alcance da arma)",
    components: { v: true, s: true, m: "uma arma corpo a corpo de 1 pe" },
    duration: "1 rodada",
    concentration: false,
    description:
      "Você brandir a arma e faz um ataque corpo a corpo. Se o alvo se mover voluntariamente antes do início do seu próximo turno, ele sofre dano trovejante.",
  },
  {
    id: "green-flame-blade",
    name: "Lâmina da Chama Esverdeada",
    level: 0,
    school: "evocation",
    ritual: false,
    castingTime: "1 ação",
    range: "Pessoal (alcance da arma)",
    components: { v: true, s: true, m: "uma arma corpo a corpo de 1 pe" },
    duration: "Instantânea",
    concentration: false,
    description:
      "Você brandir a arma e faz um ataque corpo a corpo. Em um acerto, chama verde salta para outra criatura próxima, causando dano de fogo.",
  },
  {
    id: "lightning-lure",
    name: "Chicote Elétrico",
    level: 0,
    school: "evocation",
    ritual: false,
    castingTime: "1 ação",
    range: "4,5 metros",
    components: { v: true, s: false, m: null },
    duration: "Instantânea",
    concentration: false,
    description:
      "Você cria um chicote de energia elétrica que puxa uma criatura em direção a você. Se ela falhar na salvaguarda de Força, é puxada até 3 metros e sofre dano elétrico se estiver a até 1,5 m de você.",
  },
  {
    id: "sword-burst",
    name: "Rompante de Espadas",
    level: 0,
    school: "conjuration",
    ritual: false,
    castingTime: "1 ação",
    range: "Pessoal (1,5 metro)",
    components: { v: true, s: false, m: null },
    duration: "Instantânea",
    concentration: false,
    description:
      "Você cria efêmeras lâminas espectrais ao seu redor. Cada criatura no alcance deve fazer uma salvaguarda de Destreza ou sofrer dano de energia.",
  },
  {
    id: "thunderclap",
    name: "Golpe Trovejante",
    level: 0,
    school: "evocation",
    ritual: false,
    castingTime: "1 ação",
    range: "Pessoal (1,5 metro)",
    components: { v: false, s: true, m: null },
    duration: "Instantânea",
    concentration: false,
    description:
      "Você cria um estrondo trovejante audível a até 30 metros. Cada criatura no alcance, exceto você, deve fazer uma salvaguarda de Constituição ou sofrer dano trovejante.",
  },
  {
    id: "create-bonfire",
    name: "Criar Fogueira",
    level: 0,
    school: "conjuration",
    ritual: false,
    castingTime: "1 ação",
    range: "18 metros",
    components: { v: true, s: true, m: null },
    duration: "Concentração, até 1 minuto",
    concentration: true,
    description:
      "Você cria uma fogueira em um cubo de 1,5 m. Qualquer criatura no espaço ao conjurar ou que entrar nele deve fazer uma salvaguarda de Destreza ou sofrer dano de fogo.",
  },
  {
    id: "magic-stone",
    name: "Pedra Encantada",
    level: 0,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação bônus",
    range: "Toque",
    components: { v: true, s: true, m: null },
    duration: "1 minuto",
    concentration: false,
    description:
      "Você toca de uma a três pedrinhas e as imbui de magia. Uma criatura pode arremessá-las ou usá-las em uma funda; o ataque usa seu modificador de conjuração e causa dano de energia.",
  },
  {
    id: "frostbite",
    name: "Picada Congelante",
    level: 0,
    school: "evocation",
    ritual: false,
    castingTime: "1 ação",
    range: "18 metros",
    components: { v: true, s: true, m: null },
    duration: "Instantânea",
    concentration: false,
    description:
      "Você causa frio numbing em uma criatura. Ela deve fazer uma salvaguarda de Constituição ou sofrer dano de frio e ter desvantagem no próximo ataque com arma antes do fim do seu próximo turno.",
  },
  {
    id: "absorb-elements",
    name: "Absorver Elementos",
    level: 1,
    school: "abjuration",
    ritual: false,
    castingTime: "1 reação",
    range: "Pessoal",
    components: { v: false, s: true, m: null },
    duration: "1 rodada",
    concentration: false,
    description:
      "Reação quando você sofreria dano ácido, frio, fogo, elétrico ou trovejante: você tem resistência a esse dano nessa instância e, no próximo ataque corpo a corpo, causa dano extra do mesmo tipo.",
  },
  {
    id: "catapult",
    name: "Catapulta",
    level: 1,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "18 metros",
    components: { v: false, s: true, m: null },
    duration: "Instantânea",
    concentration: false,
    description:
      "Você escolhe um objeto de até 2,5 kg que ninguém esteja vestindo ou carregando e o arremessa até 27 metros em linha reta. Criaturas no caminho fazem salvaguarda de Destreza contra dano de concussão.",
  },
  {
    id: "tashas-caustic-brew",
    name: "Beberagem Cáustica de Tasha",
    level: 1,
    school: "evocation",
    ritual: false,
    castingTime: "1 ação",
    range: "Pessoal (linha de 9 metros)",
    components: { v: true, s: true, m: "um pouco de ouro podre" },
    duration: "Concentração, até 1 minuto",
    concentration: true,
    description:
      "Uma linha de ácido de 9 m por 1,5 m. Cada criatura na linha faz salvaguarda de Destreza ou fica coberta de ácido, sofrendo dano ácido no início de cada um dos seus turnos até se livrar.",
  },
  {
    id: "snare",
    name: "Laço",
    level: 1,
    school: "abjuration",
    ritual: false,
    castingTime: "1 minuto",
    range: "Toque",
    components: { v: true, s: true, m: "7,5 metros de corda" },
    duration: "8 horas",
    concentration: false,
    description:
      "Você cria uma armadilha mágica quase invisível em uma área de 1,5 m. A primeira criatura Grande ou menor que entrar fica erguida e restrita se falhar na salvaguarda de Destreza.",
  },
  {
    id: "sanctuary",
    name: "Santuário",
    level: 1,
    school: "abjuration",
    ritual: false,
    castingTime: "1 ação bônus",
    range: "9 metros",
    components: { v: true, s: true, m: "um pequeno espelho de prata" },
    duration: "1 minuto",
    concentration: false,
    description:
      "Você protege uma criatura contra ataques. Até a magia acabar, qualquer criatura que tentar atacar o alvo ou conjurar magia prejudicial nele deve fazer uma salvaguarda de Sabedoria ou escolher um novo alvo.",
  },
  {
    id: "magic-mouth",
    name: "Boca Encantada",
    level: 2,
    school: "illusion",
    ritual: true,
    castingTime: "1 minuto",
    range: "9 metros",
    components: { v: true, s: true, m: "favo de mel e pó de jade de 10 po" },
    duration: "Até ser dissipada",
    concentration: false,
    description:
      "Você imbui um objeto com uma mensagem falada de até 25 palavras que é pronunciada quando uma condição desencadeadora que você definir ocorrer.",
  },
  {
    id: "rope-trick",
    name: "Corda Extradimensional",
    level: 2,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "Toque",
    components: { v: true, s: true, m: "pó de milho e um laço de pergaminho" },
    duration: "1 hora",
    concentration: false,
    description:
      "Você toca um pedaço de corda de até 18 m. Uma extremidade sobe e fica suspensa, abrindo um espaço extradimensional invisível no topo onde até oito criaturas Médias ou menores podem se abrigar.",
  },
  {
    id: "heat-metal",
    name: "Esquentar Metal",
    level: 2,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "18 metros",
    components: { v: true, s: true, m: "um pedaço de ferro e uma chama" },
    duration: "Concentração, até 1 minuto",
    concentration: true,
    description:
      "Escolha um objeto de metal manufaturado. Qualquer criatura em contato físico com ele sofre dano de fogo. Com uma ação bônus em turnos seguintes, você pode causar o dano novamente.",
  },
  {
    id: "skywrite",
    name: "Escrita Celeste",
    level: 2,
    school: "transmutation",
    ritual: true,
    castingTime: "1 ação",
    range: "Visão",
    components: { v: true, s: true, m: null },
    duration: "Concentração, até 1 hora",
    concentration: true,
    description:
      "Você faz com que até dez palavras apareçam em forma de nuvens no céu. A escrita é legível sob condições climáticas favoráveis e se move com o vento.",
  },
  {
    id: "pyrotechnics",
    name: "Pirotecnia",
    level: 2,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "18 metros",
    components: { v: true, s: true, m: null },
    duration: "Instantânea",
    concentration: false,
    description:
      "Escolha uma área de fogo não mágico que você possa ver. Você a extingue e cria fogos de artifício ofuscantes ou uma nuvem de fumaça densa.",
  },
  {
    id: "elemental-weapon",
    name: "Arma Elemental",
    level: 3,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "Toque",
    components: { v: true, s: true, m: null },
    duration: "Concentração, até 1 hora",
    concentration: true,
    description:
      "Uma arma não mágica se torna mágica com +1 em ataques e dano, e causa dano ácido, frio, fogo, elétrico ou trovejante extra à sua escolha.",
  },
  {
    id: "create-food-and-water",
    name: "Criar Comida e Água",
    level: 3,
    school: "conjuration",
    ritual: false,
    castingTime: "1 ação",
    range: "9 metros",
    components: { v: true, s: true, m: null },
    duration: "Instantânea",
    concentration: false,
    description:
      "Você cria 20 kg de comida e 120 litros de água no chão ou em recipientes à vista, suficientes para sustentar até quinze humanoides ou cinco montarias por 24 horas.",
  },
  {
    id: "flame-arrows",
    name: "Flechas Flamejantes",
    level: 3,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "Toque",
    components: { v: true, s: true, m: null },
    duration: "Concentração, até 1 hora",
    concentration: true,
    description:
      "Você toca um aljava com munições. Até doze peças disparam em chamas, causando dano de fogo extra em um acerto.",
  },
  {
    id: "intellect-fortress",
    name: "Fortaleza Intelectual",
    level: 3,
    school: "abjuration",
    ritual: false,
    castingTime: "1 ação",
    range: "9 metros",
    components: { v: true, s: false, m: null },
    duration: "Concentração, até 1 hora",
    concentration: true,
    description:
      "Por 1 hora, uma criatura voluntária que você possa ver ganha resistência a dano psíquico e vantagem em salvaguardas de Inteligência, Sabedoria e Carisma.",
  },
  {
    id: "glyph-of-warding",
    name: "Glifo de Proteção",
    level: 3,
    school: "abjuration",
    ritual: false,
    castingTime: "1 hora",
    range: "Toque",
    components: { v: true, s: true, m: "incenso e pó de diamante de ao menos 200 po" },
    duration: "Até ser dissipada ou ativada",
    concentration: false,
    description:
      "Você inscreve um glifo que explode ou armazena outra magia quando uma condição desencadeadora ocorre. Criaturas na área sofrem dano ou o efeito armazenado.",
  },
  {
    id: "tiny-servant",
    name: "Pequeno Servo",
    level: 3,
    school: "transmutation",
    ritual: false,
    castingTime: "1 minuto",
    range: "Toque",
    components: { v: true, s: true, m: null },
    duration: "8 horas",
    concentration: false,
    description:
      "Você toca um objeto minúsculo não mágico e o anima sob seu comando. Ele age no seu turno e segue ordens verbais simples.",
  },
  {
    id: "blink",
    name: "Piscar",
    level: 3,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "Pessoal",
    components: { v: true, s: true, m: null },
    duration: "1 minuto",
    concentration: false,
    description:
      "Role 1d20 no final de cada um dos seus turnos. Em 11 ou mais, você some para o Plano Etéreo até o início do seu próximo turno, tornando-se intangível e invisível no Plano Material.",
  },
  {
    id: "catnap",
    name: "Soneca",
    level: 3,
    school: "enchantment",
    ritual: false,
    castingTime: "1 ação",
    range: "9 metros",
    components: { v: false, s: true, m: "um beliscão de areia" },
    duration: "10 minutos",
    concentration: false,
    description:
      "Você faz até três criaturas voluntárias cair em um sono mágico. Após 10 minutos, elas ganham os benefícios de um descanso curto e não podem ser afetadas novamente por esta magia até terminarem um descanso longo.",
  },
  {
    id: "leomunds-secret-chest",
    name: "Arca Secreta de Leomund",
    level: 4,
    school: "conjuration",
    ritual: false,
    castingTime: "1 ação",
    range: "Toque",
    components: { v: true, s: true, m: "um baú requintado de 5.000 po e uma réplica miniatura de 50 po" },
    duration: "Instantânea",
    concentration: false,
    description:
      "Você esconde um baú e seu conteúdo no Plano Etéreo. Usando a réplica, você pode recuperar o baú ou devolvê-lo ao Éter. Sem a magia renovada, o baú pode se perder.",
  },
  {
    id: "mordenkainens-faithful-hound",
    name: "Cão Fiel de Mordenkainen",
    level: 4,
    school: "conjuration",
    ritual: false,
    castingTime: "1 ação",
    range: "9 metros",
    components: { v: true, s: true, m: "um minúsculo apito de prata, um pedaço de osso e um fio" },
    duration: "8 horas",
    concentration: false,
    description:
      "Você conjura um cão de guarda fantasma invisível em um local desocupado. Ele late quando uma criatura se aproxima sem a senha e pode morder intrusos.",
  },
  {
    id: "elemental-bane",
    name: "Destruição Elemental",
    level: 4,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "27 metros",
    components: { v: true, s: true, m: null },
    duration: "Concentração, até 1 minuto",
    concentration: true,
    description:
      "Escolha uma criatura e um tipo de dano (ácido, frio, fogo, elétrico ou trovejante). Ela tem desvantagem em salvaguardas contra esse dano e sofre dano extra do tipo na primeira vez que o recebe a cada turno.",
  },
  {
    id: "fabricate",
    name: "Fabricar",
    level: 4,
    school: "transmutation",
    ritual: false,
    castingTime: "10 minutos",
    range: "36 metros",
    components: { v: true, s: true, m: null },
    duration: "Instantânea",
    concentration: false,
    description:
      "Você converte matéria-prima em produtos do mesmo material. Você deve ter proficiência com as ferramentas de artesão apropriadas para fabricar objetos que normalmente as exigiriam.",
  },
  {
    id: "summon-construct",
    name: "Invocar Construto",
    level: 4,
    school: "conjuration",
    ritual: false,
    castingTime: "1 ação",
    range: "27 metros",
    components: { v: true, s: true, m: "um ornamento ornamentado de ao menos 400 po" },
    duration: "Concentração, até 1 hora",
    concentration: true,
    description:
      "Você invoca um espírito construto (argila, metal ou pedra) que aparece em um espaço desocupado. Ele é um aliado sob seu comando e desaparece ao chegar a 0 PV ou quando a magia acaba.",
  },
  {
    id: "stone-shape",
    name: "Moldar Rochas",
    level: 4,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "Toque",
    components: { v: true, s: true, m: "argila mole e algo duro" },
    duration: "Instantânea",
    concentration: false,
    description:
      "Você toca um objeto de pedra de tamanho Médio ou menor (ou uma seção de pedra de no máximo 1,5 m em qualquer dimensão) e o molda na forma que desejar.",
  },
  {
    id: "freedom-of-movement",
    name: "Movimentação Livre",
    level: 4,
    school: "abjuration",
    ritual: false,
    castingTime: "1 ação",
    range: "Toque",
    components: { v: true, s: true, m: "uma fita de couro amarrada em torno do braço" },
    duration: "1 hora",
    concentration: false,
    description:
      "O alvo fica imune a terreno difícil, restrições mágicas de movimento e pode gastar 1,5 m de movimento para escapar de não-mágicas restrições ou agarres.",
  },
  {
    id: "arcane-eye",
    name: "Olho Arcano",
    level: 4,
    school: "divination",
    ritual: false,
    castingTime: "1 ação",
    range: "9 metros",
    components: { v: true, s: true, m: "um pouco de pelo de morcego" },
    duration: "Concentração, até 1 hora",
    concentration: true,
    description:
      "Você cria um olho mágico invisível que flutua e transmite visualmente o que vê. Você pode movê-lo mentalmente até 9 metros por ação.",
  },
  {
    id: "mordenkainens-private-sanctum",
    name: "Santuário Particular de Mordenkainen",
    level: 4,
    school: "abjuration",
    ritual: false,
    castingTime: "10 minutos",
    range: "36 metros",
    components: { v: true, s: true, m: "uma folha de chumbo fina, um pedaço de espelho opaco, pó de giz e areia" },
    duration: "24 horas",
    concentration: false,
    description:
      "Você torna uma área segura contra vigilância e viagem dimensional. Sons não saem, visão é bloqueada e teletransporte ou viagem planar são impedidos conforme você escolher.",
  },
  {
    id: "animate-objects",
    name: "Animar Objetos",
    level: 5,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "36 metros",
    components: { v: true, s: true, m: null },
    duration: "Concentração, até 1 minuto",
    concentration: true,
    description:
      "Objetos não mágicos ganham vida sob seu comando. O número e o tamanho dos objetos dependem do círculo do espaço usado.",
  },
  {
    id: "skill-empowerment",
    name: "Aprimorar Perícia",
    level: 5,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "Toque",
    components: { v: true, s: true, m: null },
    duration: "Concentração, até 1 hora",
    concentration: true,
    description:
      "Você toca uma criatura voluntária e dobra seu bônus de proficiência em uma perícia à escolha em que ela seja proficiente, até o fim da magia.",
  },
  {
    id: "wall-of-stone",
    name: "Muralha de Pedra",
    level: 5,
    school: "evocation",
    ritual: false,
    castingTime: "1 ação",
    range: "36 metros",
    components: { v: true, s: true, m: "um pequeno bloco de granito" },
    duration: "Concentração, até 10 minutos",
    concentration: true,
    description:
      "Uma muralha não mágica de pedra surge em um ponto à vista. Se mantiver concentração pelo tempo total, a muralha se torna permanente.",
  },
  {
    id: "transmute-rock",
    name: "Transmutar Pedra",
    level: 5,
    school: "transmutation",
    ritual: false,
    castingTime: "1 ação",
    range: "36 metros",
    components: { v: true, s: true, m: "argila e água" },
    duration: "Até ser dissipada",
    concentration: false,
    description:
      "Você escolhe uma área de pedra ou lama e a transforma na outra (pedra em lama ou lama em pedra), afetando o terreno e criaturas na área.",
  },
];
