import type { ItemDefinition } from "@/config/types";

/** Equipamento de aventureiro padrão (PHB Cap. 5) — custos em PO. */
export const ADVENTURING_GEAR: ItemDefinition[] = [
  { id: "gear-backpack", name: "Mochila", kind: "mundane", category: "gear", rarity: "mundane", description: "Mochila de couro com compartimentos.", costGp: 2, weight: 5, source: "phb" },
  { id: "gear-bedroll", name: "Saco de Dormir", kind: "mundane", category: "gear", rarity: "mundane", description: "Saco de dormir e cobertor.", costGp: 1, weight: 7, source: "phb" },
  { id: "gear-blanket", name: "Cobertor", kind: "mundane", category: "gear", rarity: "mundane", description: "Cobertor de lã.", costGp: 0.5, weight: 3, source: "phb" },
  { id: "gear-rope-hemp", name: "Corda de Cânhamo (15 m)", kind: "mundane", category: "gear", rarity: "mundane", description: "Corda de cânhamo com 15 metros.", costGp: 1, weight: 10, source: "phb" },
  { id: "gear-rope-silk", name: "Corda de Seda (15 m)", kind: "mundane", category: "gear", rarity: "mundane", description: "Corda de seda com 15 metros.", costGp: 10, weight: 5, source: "phb" },
  { id: "gear-torch", name: "Tocha", kind: "mundane", category: "gear", rarity: "mundane", description: "Queima por 1 hora e ilumina 6 m de luz intensa.", costGp: 0.01, weight: 1, source: "phb" },
  { id: "gear-lantern-hooded", name: "Lanterna Coberta", kind: "mundane", category: "gear", rarity: "mundane", description: "Queima óleo; 9 m de luz intensa, 9 m adicional de penumbra.", costGp: 5, weight: 2, source: "phb" },
  { id: "gear-lantern-bullseye", name: "Lanterna Foco", kind: "mundane", category: "gear", rarity: "mundane", description: "Cone de 18 m de luz intensa e 18 m de penumbra.", costGp: 10, weight: 2, source: "phb" },
  { id: "gear-oil", name: "Frasco de Óleo", kind: "mundane", category: "gear", rarity: "mundane", description: "Óleo para lanternas (6 horas) ou como arma improvisada.", costGp: 0.1, weight: 1, source: "phb" },
  { id: "gear-tinderbox", name: "Caixa de Isqueiro", kind: "mundane", category: "gear", rarity: "mundane", description: "Pederneira, isqueiro e pavio para acender fogo.", costGp: 0.5, weight: 1, source: "phb" },
  { id: "gear-rations", name: "Rações (1 dia)", kind: "mundane", category: "gear", rarity: "mundane", description: "Comida seca para um dia.", costGp: 0.5, weight: 2, source: "phb" },
  { id: "gear-waterskin", name: "Cantil", kind: "mundane", category: "gear", rarity: "mundane", description: "Guarda 2 litros de líquido.", costGp: 0.2, weight: 5, source: "phb" },
  { id: "gear-mess-kit", name: "Kit de Refeição", kind: "mundane", category: "gear", rarity: "mundane", description: "Prato, talheres e caneca de estanho.", costGp: 0.2, weight: 1, source: "phb" },
  { id: "gear-healer-kit", name: "Kit de Curandeiro", kind: "mundane", category: "gear", rarity: "mundane", description: "10 usos. Estabiliza criatura morrendo com ação e teste de Sabedoria (Medicina).", costGp: 5, weight: 3, source: "phb" },
  { id: "gear-herbalism-kit", name: "Kit de Herbalismo", kind: "mundane", category: "tool", rarity: "mundane", description: "Ferramentas para identificar e preparar ervas.", costGp: 5, weight: 3, source: "phb" },
  { id: "gear-thieves-tools", name: "Ferramentas de Ladrão", kind: "mundane", category: "tool", rarity: "mundane", description: "Gazua, pequena lima, espelho e pinças.", costGp: 25, weight: 1, source: "phb" },
  { id: "gear-crowbar", name: "Pé de Cabra", kind: "mundane", category: "gear", rarity: "mundane", description: "Vantagem em testes de Força quando aplicável como alavanca.", costGp: 2, weight: 5, source: "phb" },
  { id: "gear-hammer", name: "Martelo", kind: "mundane", category: "gear", rarity: "mundane", description: "Martelo comum de trabalho.", costGp: 1, weight: 3, source: "phb" },
  { id: "gear-piton", name: "Piton", kind: "mundane", category: "gear", rarity: "mundane", description: "Espeto de metal para escalada.", costGp: 0.05, weight: 0.25, source: "phb" },
  { id: "gear-grappling-hook", name: "Gancho de Escalar", kind: "mundane", category: "gear", rarity: "mundane", description: "Gancho para lançar com corda.", costGp: 2, weight: 4, source: "phb" },
  { id: "gear-chain", name: "Corrente (3 m)", kind: "mundane", category: "gear", rarity: "mundane", description: "Corrente de 3 metros.", costGp: 5, weight: 10, source: "phb" },
  { id: "gear-manacles", name: "Algemas", kind: "mundane", category: "gear", rarity: "mundane", description: "Algemas com chave; CD 20 para escapar.", costGp: 2, weight: 6, source: "phb" },
  { id: "gear-mirror", name: "Espelho de Aço", kind: "mundane", category: "gear", rarity: "mundane", description: "Espelho polido de aço.", costGp: 5, weight: 0.5, source: "phb" },
  { id: "gear-flask", name: "Frasco Vazio", kind: "mundane", category: "gear", rarity: "mundane", description: "Frasco de cerâmica, vidro ou metal.", costGp: 0.02, weight: 1, source: "phb" },
  { id: "gear-vial", name: "Ampola", kind: "mundane", category: "gear", rarity: "mundane", description: "Ampola de vidro.", costGp: 1, weight: 0, source: "phb" },
  { id: "gear-component-pouch", name: "Bolsa de Componentes", kind: "mundane", category: "gear", rarity: "mundane", description: "Bolsa impermeável com compartimentos para componentes materiais.", costGp: 25, weight: 2, source: "phb" },
  { id: "gear-arcane-focus", name: "Foco Arcano (cristal)", kind: "mundane", category: "gear", rarity: "mundane", description: "Cristal usado como foco de conjuração arcana.", costGp: 10, weight: 1, source: "phb" },
  { id: "gear-holy-symbol", name: "Símbolo Sagrado (amuleto)", kind: "mundane", category: "gear", rarity: "mundane", description: "Amuleto representando uma divindade.", costGp: 5, weight: 1, source: "phb" },
  { id: "gear-druidic-focus", name: "Foco Druídico (ramo de visco)", kind: "mundane", category: "gear", rarity: "mundane", description: "Ramo de visco usado como foco druídico.", costGp: 1, weight: 0, source: "phb" },
  { id: "gear-spellbook", name: "Livro de Magias", kind: "mundane", category: "gear", rarity: "mundane", description: "Livro encadernado para magos registrarem magias.", costGp: 50, weight: 3, source: "phb" },
  { id: "gear-ink", name: "Tinta (30 ml)", kind: "mundane", category: "gear", rarity: "mundane", description: "Frasco de tinta preta.", costGp: 10, weight: 0, source: "phb" },
  { id: "gear-ink-pen", name: "Pena de Escrever", kind: "mundane", category: "gear", rarity: "mundane", description: "Pena para escrever.", costGp: 0.02, weight: 0, source: "phb" },
  { id: "gear-parchment", name: "Pergaminho (folha)", kind: "mundane", category: "gear", rarity: "mundane", description: "Folha de pergaminho.", costGp: 0.1, weight: 0, source: "phb" },
  { id: "gear-paper", name: "Papel (folha)", kind: "mundane", category: "gear", rarity: "mundane", description: "Folha de papel.", costGp: 0.2, weight: 0, source: "phb" },
  { id: "gear-chalk", name: "Giz (1 peça)", kind: "mundane", category: "gear", rarity: "mundane", description: "Pedaço de giz.", costGp: 0.01, weight: 0, source: "phb" },
  { id: "gear-climbers-kit", name: "Kit de Escalada", kind: "mundane", category: "gear", rarity: "mundane", description: "Pitons, botas, luvas e arreio. Vantagem para escalar em alguns casos.", costGp: 25, weight: 12, source: "phb" },
  { id: "gear-fishing-tackle", name: "Equipamento de Pesca", kind: "mundane", category: "gear", rarity: "mundane", description: "Vara, linha, anzóis e iscas.", costGp: 1, weight: 4, source: "phb" },
  { id: "gear-hunting-trap", name: "Armadilha de Caça", kind: "mundane", category: "gear", rarity: "mundane", description: "Armadilha de aço; CD 13 para detectar/escapar.", costGp: 5, weight: 25, source: "phb" },
  { id: "gear-magnifying-glass", name: "Lupa", kind: "mundane", category: "gear", rarity: "mundane", description: "Lente de aumento; ajuda em inspeções detalhadas.", costGp: 100, weight: 0, source: "phb" },
  { id: "gear-scale", name: "Balança de Mercador", kind: "mundane", category: "gear", rarity: "mundane", description: "Balança e pesos para medir até 1 kg.", costGp: 5, weight: 3, source: "phb" },
  { id: "gear-signal-whistle", name: "Apito de Sinalização", kind: "mundane", category: "gear", rarity: "mundane", description: "Apito audível a distância.", costGp: 0.05, weight: 0, source: "phb" },
  { id: "gear-iron-pot", name: "Panela de Ferro", kind: "mundane", category: "gear", rarity: "mundane", description: "Panela para cozinhar.", costGp: 2, weight: 10, source: "phb" },
  { id: "gear-shovel", name: "Pá", kind: "mundane", category: "gear", rarity: "mundane", description: "Pá de cavar.", costGp: 2, weight: 5, source: "phb" },
  { id: "gear-tent", name: "Tenda de Duas Pessoas", kind: "mundane", category: "gear", rarity: "mundane", description: "Tenda simples para duas criaturas Médias.", costGp: 2, weight: 20, source: "phb" },
  { id: "gear-soap", name: "Sabão", kind: "mundane", category: "gear", rarity: "mundane", description: "Barra de sabão.", costGp: 0.02, weight: 0, source: "phb" },
  { id: "gear-perfume", name: "Perfume (frasco)", kind: "mundane", category: "gear", rarity: "mundane", description: "Frasco de perfume.", costGp: 5, weight: 0, source: "phb" },
  { id: "gear-poison-basic", name: "Veneno Básico (frasco)", kind: "mundane", category: "gear", rarity: "mundane", description: "Veneno para aplicar em arma; dano de veneno com salvaguarda de Constituição.", costGp: 100, weight: 0, source: "phb" },
  { id: "ammo-arrows", name: "Flechas (20)", kind: "mundane", category: "ammunition", rarity: "mundane", description: "Aljava com 20 flechas.", costGp: 1, weight: 1, source: "phb" },
  { id: "ammo-bolts", name: "Virotes de Besta (20)", kind: "mundane", category: "ammunition", rarity: "mundane", description: "Estojo com 20 virotes.", costGp: 1, weight: 1.5, source: "phb" },
  { id: "ammo-sling-bullets", name: "Projéteis de Funda (20)", kind: "mundane", category: "ammunition", rarity: "mundane", description: "Bolsa com 20 projéteis.", costGp: 0.04, weight: 1.5, source: "phb" },
  { id: "ammo-blowgun-needles", name: "Agulhas de Zarabatana (50)", kind: "mundane", category: "ammunition", rarity: "mundane", description: "Estojo com 50 agulhas.", costGp: 1, weight: 1, source: "phb" },
];
