"""Full PT-BR translation pass for magic item descriptions."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN_PATH = ROOT / "content/items/magic-items-basic-rules.en.json"
PT_PATH = ROOT / "content/items/magic-items-basic-rules.pt.json"
SLIM = ROOT / "src/config/items/magicItemsData.json"

# Longest-first phrase map (EN → PT-BR)
PHRASES: list[tuple[str, str]] = [
    ("Claim the Dungeon Masters: Living Spells Play-Along Pack", ""),
    ("Magic Items (A)", ""),
    ("Magic Items (B)", ""),
    ("Magic Items (C)", ""),
    ("Magic Items (D)", ""),
    ("Magic Items (E)", ""),
    ("Magic Items (F)", ""),
    ("Magic Items (G)", ""),
    ("Magic Items (H)", ""),
    ("Magic Items (I)", ""),
    ("Magic Items (J)", ""),
    ("Magic Items (K)", ""),
    ("Magic Items (L)", ""),
    ("Magic Items (M)", ""),
    ("Magic Items (N)", ""),
    ("Magic Items (O)", ""),
    ("Magic Items (P)", ""),
    ("Magic Items (Q)", ""),
    ("Magic Items (R)", ""),
    ("Magic Items (S)", ""),
    ("Magic Items (T)", ""),
    ("Magic Items (U)", ""),
    ("Magic Items (V)", ""),
    ("Magic Items (W)", ""),
    ("Magic Items (X)", ""),
    ("Magic Items (Y)", ""),
    ("Magic Items (Z)", ""),
    ("Requires Attunement by a spellcaster", "Requer sintonização por um conjurador"),
    ("Requires Attunement by a creature", "Requer sintonização por uma criatura"),
    ("Requires Attunement by a", "Requer sintonização por um(a)"),
    ("Requires Attunement", "Requer sintonização"),
    ("requires attunement", "requer sintonização"),
    ("Wondrous Item", "Item Maravilhoso"),
    ("Bonus Action", "Ação Bônus"),
    ("bonus action", "ação bônus"),
    ("Magic action", "ação de Magia"),
    ("Utilize action", "ação de Utilizar"),
    ("Critical Hit", "Acerto Crítico"),
    ("critical hit", "acerto crítico"),
    ("Hit Points", "Pontos de Vida"),
    ("hit points", "pontos de vida"),
    ("Hit Point", "Ponto de Vida"),
    ("Armor Class", "Classe de Armadura"),
    ("armor class", "classe de armadura"),
    ("Saving Throw", "Teste de Resistência"),
    ("saving throw", "teste de resistência"),
    ("Ability Check", "Teste de Atributo"),
    ("ability check", "teste de atributo"),
    ("attack rolls and damage rolls", "rolagens de ataque e de dano"),
    ("attack rolls", "rolagens de ataque"),
    ("attack roll", "rolagem de ataque"),
    ("damage rolls", "rolagens de dano"),
    ("damage roll", "rolagem de dano"),
    ("Long Rest", "Descanso Longo"),
    ("long rest", "descanso longo"),
    ("Short Rest", "Descanso Curto"),
    ("short rest", "descanso curto"),
    ("spell save DC", "CD de resistência da magia"),
    ("Spellcasting Ability", "Atributo de Conjuração"),
    ("spell attack", "ataque mágico"),
    ("Spell Attack", "Ataque Mágico"),
    ("Difficult Terrain", "Terreno Difícil"),
    ("Diﬃcult Terrain", "Terreno Difícil"),
    ("Dim Light", "Penumbra"),
    ("Bright Light", "Luz Intensa"),
    ("Darkvision", "Visão no Escuro"),
    ("Climb Speed", "Deslocamento de Escalada"),
    ("Fly Speed", "Deslocamento de Voo"),
    ("Swim Speed", "Deslocamento de Natação"),
    ("Walking Speed", "Deslocamento"),
    ("Initiative count", "contagem de Iniciativa"),
    ("Advantage on", "vantagem em"),
    ("Disadvantage on", "desvantagem em"),
    ("have Advantage", "têm vantagem"),
    ("have Disadvantage", "têm desvantagem"),
    ("has Advantage", "tem vantagem"),
    ("has Disadvantage", "tem desvantagem"),
    ("You have Advantage", "Você tem vantagem"),
    ("You have Disadvantage", "Você tem desvantagem"),
    ("You gain a", "Você ganha um"),
    ("You gain", "Você ganha"),
    ("You have Resistance to", "Você tem Resistência a"),
    ("You have Immunity to", "Você tem Imunidade a"),
    ("You have Vulnerability to", "Você tem Vulnerabilidade a"),
    ("you have Resistance to", "você tem Resistência a"),
    ("you have Immunity to", "você tem Imunidade a"),
    ("While you're wearing it", "Enquanto você a vestir"),
    ("While you’re wearing it", "Enquanto você a vestir"),
    ("While you wear", "Enquanto você vestir"),
    ("while you wear", "enquanto você vestir"),
    ("While wearing", "Enquanto vestir"),
    ("while wearing", "enquanto vestir"),
    ("While holding", "Enquanto segurar"),
    ("while holding", "enquanto segurar"),
    ("While you are within", "Enquanto você estiver a até"),
    ("while you are within", "enquanto você estiver a até"),
    ("While touching", "Enquanto tocar"),
    ("while touching", "enquanto tocar"),
    ("You can take a", "Você pode gastar uma"),
    ("you can take a", "você pode gastar uma"),
    ("You can use an action", "Você pode usar uma ação"),
    ("you can use an action", "você pode usar uma ação"),
    ("You can use a bonus action", "Você pode usar uma ação bônus"),
    ("As a Magic action", "Como uma ação de Magia"),
    ("as a Magic action", "como uma ação de Magia"),
    ("As an action", "Como uma ação"),
    ("as an action", "como uma ação"),
    ("As a bonus action", "Como uma ação bônus"),
    ("as a bonus action", "como uma ação bônus"),
    ("Once this property is used, it can't be used again until the next dawn",
     "Depois de usar esta propriedade, ela não pode ser usada novamente até o próximo amanhecer"),
    ("Once used, this property can't be used again until the next dawn",
     "Depois de usada, esta propriedade não pode ser usada novamente até o próximo amanhecer"),
    ("can't be used again until the next dawn", "não pode ser usada novamente até o próximo amanhecer"),
    ("can't be used this way again until the next dawn",
     "não pode ser usada desta forma novamente até o próximo amanhecer"),
    ("regains all expended charges daily at dawn", "recupera todas as cargas gastas diariamente ao amanhecer"),
    ("regains 1d6 expended charges daily at dawn", "recupera 1d6 cargas gastas diariamente ao amanhecer"),
    ("regains 1d3 expended charges daily at dawn", "recupera 1d3 cargas gastas diariamente ao amanhecer"),
    ("daily at dawn", "diariamente ao amanhecer"),
    ("until the next dawn", "até o próximo amanhecer"),
    ("the next dawn", "o próximo amanhecer"),
    ("Bludgeoning, Piercing, and Slashing damage", "dano de Concussão, Perfurante e Cortante"),
    ("Bludgeoning, Piercing, or Slashing", "Concussão, Perfurante ou Cortante"),
    ("Bludgeoning", "Concussão"),
    ("Piercing", "Perfurante"),
    ("Slashing", "Cortante"),
    ("Poison damage", "dano de Veneno"),
    ("Fire damage", "dano de Fogo"),
    ("Cold damage", "dano de Frio"),
    ("Lightning damage", "dano de Relâmpago"),
    ("Thunder damage", "dano de Trovão"),
    ("Acid damage", "dano de Ácido"),
    ("Necrotic damage", "dano de Necrótico"),
    ("Radiant damage", "dano Radiante"),
    ("Force damage", "dano de Energia"),
    ("Psychic damage", "dano Psíquico"),
    ("Poisoned condition", "condição Envenenado"),
    ("Invisible condition", "condição Invisível"),
    ("this magic item", "este item mágico"),
    ("This magic item", "Este item mágico"),
    ("magical weapon", "arma mágica"),
    ("magic weapon", "arma mágica"),
    ("magic ammunition", "munição mágica"),
    ("nonmagical", "não mágico"),
    ("Attuning to", "Sintonizar-se com"),
    ("attune to", "sintonizar-se com"),
    ("attuned to", "sintonizado com"),
    ("Attunement", "Sintonização"),
    ("attunement", "sintonização"),
    ("charges", "cargas"),
    ("charge", "carga"),
    ("rarity", "raridade"),
    ("Very Rare", "muito rara"),
    ("Uncommon", "incomum"),
    ("Legendary", "lendária"),
    ("Artifact", "artefato"),
    ("Common", "comum"),
    (" Rare", " rara"),
    (" Strength", " Força"),
    (" Dexterity", " Destreza"),
    (" Constitution", " Constituição"),
    (" Intelligence", " Inteligência"),
    (" Wisdom", " Sabedoria"),
    (" Charisma", " Carisma"),
    ("(Stealth)", "(Furtividade)"),
    ("(Investigation)", "(Investigação)"),
    ("(Perception)", "(Percepção)"),
    ("(Arcana)", "(Arcanismo)"),
    ("(History)", "(História)"),
    ("(Nature)", "(Natureza)"),
    ("(Religion)", "(Religião)"),
    ("(Athletics)", "(Atletismo)"),
    ("(Acrobatics)", "(Acrobacia)"),
    ("Monster Manual", "Manual dos Monstros"),
    ("Material Plane", "Plano Material"),
    ("Outer Plane", "Plano Exterior"),
    ("this armor", "esta armadura"),
    ("this weapon", "esta arma"),
    ("this shield", "este escudo"),
    ("this amulet", "este amuleto"),
    ("this cloak", "este manto"),
    ("this ring", "este anel"),
    ("this bag", "esta bolsa"),
    ("this potion", "esta poção"),
    ("this wand", "esta varinha"),
    ("this staff", "este cajado"),
    ("this rod", "este bastão"),
    ("You have a bonus to", "Você tem um bônus em"),
    ("you have a bonus to", "você tem um bônus em"),
    ("The bonus is determined by", "O bônus é determinado por"),
    ("The DM chooses", "O Mestre escolhe"),
    ("the DM chooses", "o Mestre escolhe"),
    ("determined randomly", "determinado aleatoriamente"),
    ("or determines it randomly", "ou determina aleatoriamente"),
    ("Once it hits a target", "Quando acerta um alvo"),
    ("is no longer magical", "deixa de ser mágica"),
    ("It has no effect on you if", "Não tem efeito em você se"),
    ("without it", "sem ele"),
    ("or higher", "ou maior"),
    ("you can't be targeted by", "você não pode ser alvo de"),
    ("you can’t be targeted by", "você não pode ser alvo de"),
    ("Divination spells", "magias de Adivinhação"),
    ("magical scrying sensors", "sensores mágicos de vidência"),
    ("unless you allow it", "a menos que você permita"),
    ("cause it to animate", "fazê-lo se animar"),
    ("leaps into the air and hovers", "salta no ar e flutua"),
    ("in your space", "no seu espaço"),
    ("Friendly to you and your allies", "Amigável a você e aos seus aliados"),
    ("Friendly to you", "Amigável a você"),
    ("stat block", "bloco de estatísticas"),
    ("reduced to 0", "reduzido a 0"),
    ("unoccupied space", "espaço desocupado"),
    ("command word", "palavra de comando"),
    ("using the", "usando o/a"),
    ("This suit of armor is reinforced with adamantine, one of the hardest substances in existence.",
     "Esta armadura é reforçada com adamantina, uma das substâncias mais duras existentes."),
    ("any Acerto Crítico against you becomes a normal hit.",
     "qualquer Acerto Crítico contra você se torna um acerto normal."),
    ("Your Constituição is 19", "Sua Constituição é 19"),
    ("your Constituição is 19", "sua Constituição é 19"),
]


WORD_MAP = [
    (r"\bYou\b", "Você"),
    (r"\byou\b", "você"),
    (r"\bYour\b", "Seu/Sua"),
    (r"\byour\b", "seu/sua"),
    (r"\bThis\b", "Este/Esta"),
    (r"\bthis\b", "este/esta"),
    (r"\bThat\b", "Aquele/Aquela"),
    (r"\bWhen\b", "Quando"),
    (r"\bwhen\b", "quando"),
    (r"\bWhile\b", "Enquanto"),
    (r"\bwhile\b", "enquanto"),
    (r"\bIf\b", "Se"),
    (r"\bif\b", "se"),
    (r"\bUntil\b", "Até"),
    (r"\buntil\b", "até"),
    (r"\band\b", "e"),
    (r"\bor\b", "ou"),
    (r"\bwith\b", "com"),
    (r"\bwithout\b", "sem"),
    (r"\bfrom\b", "de"),
    (r"\binto\b", "para"),
    (r"\bonto\b", "sobre"),
    (r"\bagainst\b", "contra"),
    (r"\bduring\b", "durante"),
    (r"\bbefore\b", "antes"),
    (r"\bafter\b", "depois"),
    (r"\bmust\b", "deve"),
    (r"\bcan\b", "pode"),
    (r"\bcannot\b", "não pode"),
    (r"\bcan’t\b", "não pode"),
    (r"\bcan't\b", "não pode"),
    (r"\bwon't\b", "não vai"),
    (r"\bwon't\b", "não vai"),
    (r"\bis\b", "é"),
    (r"\bare\b", "são"),
    (r"\bwas\b", "foi"),
    (r"\bwere\b", "foram"),
    (r"\bbe\b", "ser"),
    (r"\bbeen\b", "sido"),
    (r"\bbeing\b", "sendo"),
    (r"\bhave\b", "tem"),
    (r"\bhas\b", "tem"),
    (r"\bhad\b", "tinha"),
    (r"\bdo\b", "faz"),
    (r"\bdoes\b", "faz"),
    (r"\bdid\b", "fez"),
    (r"\bnot\b", "não"),
    (r"\bno\b", "nenhum"),
    (r"\bany\b", "qualquer"),
    (r"\beach\b", "cada"),
    (r"\ball\b", "todos"),
    (r"\bonce\b", "uma vez"),
    (r"\bagain\b", "novamente"),
    (r"\balso\b", "também"),
    (r"\bonly\b", "apenas"),
    (r"\bstill\b", "ainda"),
    (r"\balready\b", "já"),
    (r"\bthen\b", "então"),
    (r"\bthan\b", "do que"),
    (r"\bsuch\b", "tal"),
    (r"\bother\b", "outro"),
    (r"\banother\b", "outro"),
    (r"\bsame\b", "mesmo"),
    (r"\bmore\b", "mais"),
    (r"\bmost\b", "maioria"),
    (r"\bless\b", "menos"),
    (r"\bup to\b", "até"),
    (r"\bat least\b", "pelo menos"),
    (r"\binstead\b", "em vez disso"),
    (r"\bcreature\b", "criatura"),
    (r"\bcreatures\b", "criaturas"),
    (r"\btarget\b", "alvo"),
    (r"\btargets\b", "alvos"),
    (r"\benemy\b", "inimigo"),
    (r"\benemies\b", "inimigos"),
    (r"\bally\b", "aliado"),
    (r"\ballies\b", "aliados"),
    (r"\bweapon\b", "arma"),
    (r"\bweapons\b", "armas"),
    (r"\barmor\b", "armadura"),
    (r"\bshield\b", "escudo"),
    (r"\bspells?\b", "magia"),
    (r"\bmagical\b", "mágico"),
    (r"\bmagic\b", "mágica"),
    (r"\bitem\b", "item"),
    (r"\bitems\b", "itens"),
    (r"\bproperty\b", "propriedade"),
    (r"\bproperties\b", "propriedades"),
    (r"\beffect\b", "efeito"),
    (r"\beffects\b", "efeitos"),
    (r"\bdamage\b", "dano"),
    (r"\bbonus\b", "bônus"),
    (r"\bradius\b", "raio"),
    (r"\bsphere\b", "esfera"),
    (r"\bcone\b", "cone"),
    (r"\bline\b", "linha"),
    (r"\bminute\b", "minuto"),
    (r"\bminutes\b", "minutos"),
    (r"\bhour\b", "hora"),
    (r"\bhours\b", "horas"),
    (r"\bround\b", "rodada"),
    (r"\brounds\b", "rodadas"),
    (r"\bturn\b", "turno"),
    (r"\bturns\b", "turnos"),
    (r"\bday\b", "dia"),
    (r"\bdays\b", "dias"),
    (r"\bdawn\b", "amanhecer"),
    (r"\bdusk\b", "crepúsculo"),
    (r"\bground\b", "chão"),
    (r"\bair\b", "ar"),
    (r"\bwater\b", "água"),
    (r"\bfire\b", "fogo"),
    (r"\blight\b", "luz"),
    (r"\bdarkness\b", "escuridão"),
    (r"\bspeed\b", "deslocamento"),
    (r"\bweight\b", "peso"),
    (r"\bpound\b", "libra"),
    (r"\bpounds\b", "libras"),
    (r"\binch\b", "polegada"),
    (r"\binches\b", "polegadas"),
    (r"\bfoot\b", "pé"),
    (r"\bfeet\b", "pés"),
    (r"\bReaction\b", "Reação"),
    (r"\breaction\b", "reação"),
    (r"\bAction\b", "Ação"),
    (r"\baction\b", "ação"),
    (r"\bResistance\b", "Resistência"),
    (r"\bImmunity\b", "Imunidade"),
    (r"\bVulnerability\b", "Vulnerabilidade"),
    (r"\bFriendly\b", "Amigável"),
    (r"\bHostile\b", "Hostil"),
    (r"\bInvisible\b", "Invisível"),
    (r"\bPoisoned\b", "Envenenado"),
    (r"\bcurse\b", "maldição"),
    (r"\bCursed\b", "Amaldiçoado"),
    (r"\bCurse\b", "Maldição"),
    (r"\bremove\b", "remover"),
    (r"\bwearing\b", "vestindo"),
    (r"\bwear\b", "vestir"),
    (r"\bwield\b", "empunhar"),
    (r"\bholding\b", "segurando"),
    (r"\bhold\b", "segurar"),
    (r"\bthrow\b", "arremessar"),
    (r"\bcast\b", "conjur"),
    (r"\bcast\b", "conjurar"),
    (r"\bexpend\b", "gastar"),
    (r"\bexpended\b", "gastas"),
    (r"\bregain\b", "recuperar"),
    (r"\bregains\b", "recupera"),
    (r"\bsucceed on a\b", "passar em um"),
    (r"\bmust succeed on a\b", "deve passar em um"),
    (r"\bmakes a\b", "faz um"),
    (r"\bmake a\b", "faça um"),
    (r"\bfailed save\b", "falha na salvaguarda"),
    (r"\bsuccessful one\b", "sucesso"),
    (r"\bhalf as much damage\b", "metade do dano"),
    (r"\bon a failed save\b", "em uma falha"),
    (r"\bon a successful one\b", "em um sucesso"),
    (r"\bDC\b", "CD"),
]


def feet_to_m(text: str) -> str:
    def repl(m: re.Match[str]) -> str:
        n = int(m.group(1))
        meters = round(n * 0.3, 1)
        if float(meters).is_integer():
            meters = int(meters)
        return f"{meters} metros"

    text = re.sub(r"(\d+)\s*[-–]?\s*foot(?:-radius)?", repl, text, flags=re.I)
    text = re.sub(r"(\d+)\s*feet", repl, text, flags=re.I)
    text = re.sub(r"(\d+)\s*ft\.?", repl, text, flags=re.I)
    return text


def translate(text: str) -> str:
    s = text
    # ligatures
    s = s.replace("ﬁ", "fi").replace("ﬂ", "fl").replace("ﬀ", "ff").replace("ﬃ", "ffi")
    for en, pt in sorted(PHRASES, key=lambda x: len(x[0]), reverse=True):
        s = s.replace(en, pt)
    s = feet_to_m(s)
    for pat, rep in WORD_MAP:
        s = re.sub(pat, rep, s)
    s = re.sub(r"\s{2,}", " ", s).strip()
    s = re.sub(r"\s+([.,;:])", r"\1", s)
    return s


TYPE_MAP = [
    ("Wondrous Item", "Item Maravilhoso"),
    ("Requires Attunement", "Requer sintonização"),
    ("Any Medium or Heavy, Except Hide Armor", "qualquer média ou pesada, exceto armadura de pele"),
    ("Any Light, Medium, or Heavy", "qualquer leve, média ou pesada"),
    ("Any Ammunition", "qualquer munição"),
    ("Plate Armor", "Armadura de Placas"),
    ("Shield", "Escudo"),
    ("Armor", "Armadura"),
    ("Weapon", "Arma"),
    ("Potion", "Poção"),
    ("Ring", "Anel"),
    ("Rod", "Bastão"),
    ("Staff", "Cajado"),
    ("Wand", "Varinha"),
    ("Scroll", "Pergaminho"),
    ("Very Rare", "Muito Rara"),
    ("Uncommon", "Incomum"),
    ("Legendary", "Lendária"),
    ("Artifact", "Artefato"),
    ("Common", "Comum"),
    ("Rare", "Rara"),
]


def translate_type(line: str) -> str:
    s = line
    for a, b in TYPE_MAP:
        s = s.replace(a, b)
    return s


EN_LEFTOVER = re.compile(
    r"\b(While|You|Your|This|That|When|Requires|Attunement|Bonus Action|"
    r"Hit Points|Armor Class|Saving Throw|attack roll|damage roll|feet|"
    r"Wondrous|Uncommon|Legendary|creature|creatures|wearing|holding|"
    r"can't|cannot|once|until|dawn|charges?)\b",
    re.I,
)


def main() -> None:
    en_items = {i["id"]: i for i in json.loads(EN_PATH.read_text(encoding="utf-8"))}
    pt_items = json.loads(PT_PATH.read_text(encoding="utf-8"))
    # keep only ids present in PT (already cleaned)
    leftover = []
    for it in pt_items:
        src = en_items.get(it["id"], it)
        desc_en = src.get("descriptionEn") or it.get("descriptionEn") or ""
        it["descriptionPt"] = translate(desc_en)
        it["typeLinePt"] = translate_type(src.get("typeLineEn") or it.get("typeLineEn") or "")
        if EN_LEFTOVER.search(it["descriptionPt"]):
            leftover.append(it["id"])
        it["translationMethod"] = "full-glossary-v2"

    PT_PATH.write_text(json.dumps(pt_items, ensure_ascii=False, indent=2), encoding="utf-8")

    slim = []
    for i in pt_items:
        slim.append(
            {
                "id": i["id"],
                "name": i["namePt"] or i["nameEn"],
                "nameEn": i["nameEn"],
                "category": i["category"],
                "typeLine": i.get("typeLinePt") or "",
                "rarity": i["rarity"],
                "requiresAttunement": i["requiresAttunement"],
                "description": i["descriptionPt"],
                "source": "basic-rules",
                "variants": i.get("variants") or [],
            }
        )
    SLIM.write_text(json.dumps(slim, ensure_ascii=False, indent=2), encoding="utf-8")

    report = ROOT / "content/items/TRANSLATION_AUDIT.md"
    report.write_text(
        "\n".join(
            [
                "# Auditoria de tradução PT-BR",
                "",
                f"- Itens: {len(pt_items)}",
                f"- Descrições ainda com possíveis resíduos EN: **{len(leftover)}**",
                "",
                "## IDs com resíduo EN detectado",
                "",
                *[f"- `{x}`" for x in leftover[:100]],
                ("…" if len(leftover) > 100 else ""),
            ]
        ),
        encoding="utf-8",
    )
    print(f"translated {len(pt_items)}; leftover_flags={len(leftover)}")


if __name__ == "__main__":
    main()
